description = "The just-bin-it histogrammer."

devices = dict(
    jbi_detector=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItDetector",
        description="The just-bin-it histogrammer",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="",
        event_schema="ev44",
        hist_schema="hs01",
        liveinterval=5,
        timeoutinterval=30,
        command_topic="nmx_jbi_commands",
        response_topic="nmx_jbi_responses",
        statustopic=["nmx_jbi_heartbeat"],
        images=[
            "det_p0_data",
            "det_p1_data",
            "det_p2_data",
            "mon_1_data",
            "mon_2_data",
            "mon_3_data",
        ],
        timers=["timer"],
    ),
    timer=device(
        "nicos_ess.devices.timer.TimerChannel",
        description="Timer",
        fmtstr="%.2f",
        unit="s",
    ),
    det_p0_data=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="nmx_visualisation",
        data_topic="nmx_detector_p0",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=1280,
        det_height=1280,
        det_range=(1, 1638400),
    ),
    det_p1_data=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="nmx_visualisation",
        data_topic="nmx_detector_p1",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=1280,
        det_height=1280,
        det_range=(1638401, 3276800),
    ),
    det_p2_data=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="nmx_visualisation",
        data_topic="nmx_detector_p2",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=1280,
        det_height=1280,
        det_range=(3276801, 4915200),
    ),
    mon_1_data=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="nmx_beam_monitor",
        source="cbm1",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        det_width=1,
        det_height=1,
        tof_range=(0, 71428000),
        num_bins=744,
        hist_topic="nmx_visualisation",
        input_schema="da00",
    ),
    mon_2_data=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="nmx_beam_monitor",
        hist_topic="nmx_visualisation",
        source="cbm2",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=32,
        det_height=32,
    ),
    mon_3_data=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="nmx_beam_monitor",
        source="cbm3",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        hist_topic="nmx_visualisation",
    ),
)

startupcode = """
SetDetectors(jbi_detector)
"""
