description = "The choppers for BIFROST"

pv_root_1 = "BIFRO-ChpSy2:Chop-BWC-101:"
pv_root_2 = "BIFRO-ChpSy2:Chop-BWC-102:"
chic_root = "BIFRO-ChpSy2:Chop-CHIC-001:"

devices = dict(
    bwc1_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{pv_root_1}ChopState_R",
        visibility=(),
    ),
    bwc1_chopper_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv=f"{pv_root_1}C_Execute",
        writepv=f"{pv_root_1}C_Execute",
        requires={"level": "admin"},
        visibility=(),
    ),
    bwc1_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{pv_root_1}Spd_R",
        writepv=f"{pv_root_1}Spd_S",
        precision=0.1,
        mapping={"-14 Hz": -14, "0 Hz": 0, "14 Hz": 14},
    ),
    bwc1_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{pv_root_1}ChopDly-S",
        writepv=f"{pv_root_1}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    bwc1_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="bwc1_chopper_delay",
        mapped_speed_dev="bwc1_chopper_speed",
        offset=0,
        unit="degrees",
    ),
    bwc1_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{pv_root_1}DiffTSSamples",
        unit="ns",
        visibility=(
            "metadata",
            "namespace",
        ),
    ),
    bwc1_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{pv_root_1}InPhs_R",
    ),
    bwc1_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{pv_root_1}Pos_R",
        writepv=f"{pv_root_1}Park_S",
        visibility=(),
    ),
    bwc1_chopper_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv=f"{chic_root}ConnectedR",
        visibility=(),
        pva=True,
    ),
    bwc1_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.ChopperAlarms",
        description="The chopper alarms",
        pv_root=pv_root_1,
        visibility=(),
    ),
    bwc1_chopper=device(
        "nicos_ess.devices.epics.chopper.EssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="bwc1_chopper_status",
        command="bwc1_chopper_control",
        speed="bwc1_chopper_speed",
        chic_conn="bwc1_chopper_chic",
        alarms="bwc1_chopper_alarms",
        slit_edges=[[0.0, 161.0]],
    ),
    bwc2_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{pv_root_2}ChopState_R",
        visibility=(),
    ),
    bwc2_chopper_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv=f"{pv_root_2}C_Execute",
        writepv=f"{pv_root_2}C_Execute",
        requires={"level": "admin"},
        visibility=(),
    ),
    bwc2_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{pv_root_2}Spd_R",
        writepv=f"{pv_root_2}Spd_S",
        precision=0.1,
        mapping={"-14 Hz": -14, "0 Hz": 0, "14 Hz": 14},
    ),
    bwc2_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{pv_root_2}ChopDly-S",
        writepv=f"{pv_root_2}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    bwc2_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="bwc2_chopper_delay",
        mapped_speed_dev="bwc2_chopper_speed",
        offset=0,
        unit="degrees",
    ),
    bwc2_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{pv_root_2}DiffTSSamples",
        unit="ns",
        visibility=(
            "metadata",
            "namespace",
        ),
    ),
    bwc2_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{pv_root_2}InPhs_R",
    ),
    bwc2_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{pv_root_2}Pos_R",
        writepv=f"{pv_root_2}Park_S",
        visibility=(),
    ),
    bwc2_chopper_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv=f"{chic_root}ConnectedR",
        visibility=(),
    ),
    bwc2_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.ChopperAlarms",
        description="The chopper alarms",
        pv_root=pv_root_2,
        visibility=(),
    ),
    bwc2_chopper=device(
        "nicos_ess.devices.epics.chopper.EssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="bwc2_chopper_status",
        command="bwc2_chopper_control",
        speed="bwc2_chopper_speed",
        chic_conn="bwc2_chopper_chic",
        alarms="bwc2_chopper_alarms",
        slit_edges=[[0.0, 161.0]],
    ),
)
