description = "The just-bin-it histogrammer."

excludes = ["livedata"]

devices = dict(
    detector_image=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="bifrost_visualisation",
        data_topic="bifrost_detector",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=900,
        det_height=15,
        det_range=(1, 13500),
        tof_range=(0, 71428571),
    ),
    detector_tof=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="bifrost_visualisation",
        data_topic="bifrost_detector",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        det_width=900,
        det_height=15,
        det_range=(1, 13500),
        tof_range=(0, 71428571),
    ),
    psc_monitor=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="bifrost_visualisation",
        data_topic="bifrost_beam_monitor",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        det_width=1,
        det_height=1,
        det_range=(0, 100),
        tof_range=(0, 71428571),
        num_bins=744,
        input_schema="da00",
        source="cbm1",
    ),
    overlap_monitor=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="bifrost_visualisation",
        data_topic="bifrost_beam_monitor",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="ADC counts",
        hist_type="1-D TOF",
        det_width=1,
        det_height=1,
        det_range=(0, 100),
        tof_range=(0, 71428571),
        num_bins=744,
        input_schema="da00",
        source="cbm2",
    ),
    bandwidth_monitor=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="bifrost_visualisation",
        data_topic="bifrost_beam_monitor",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="ADC counts",
        hist_type="1-D TOF",
        det_width=1,
        det_height=1,
        det_range=(0, 100),
        tof_range=(0, 71428571),
        num_bins=744,
        input_schema="da00",
        source="cbm3",
    ),
    normalization_monitor=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="bifrost_visualisation",
        data_topic="bifrost_beam_monitor",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        det_width=32,
        det_height=32,
        det_range=(1, 1024),
        tof_range=(0, 71428571),
        num_bins=744,
        input_schema="ev44",
        source="cbm4",
    ),
    elastic_monitor=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="bifrost_visualisation",
        data_topic="bifrost_beam_monitor",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        det_width=1,
        det_height=1,
        det_range=(1, 1),
        tof_range=(0, 71428571),
        num_bins=744,
        input_schema="ev44",
        source="cbm5",
    ),
    jbi_detector=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItDetector",
        description="The just-bin-it histogrammer",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="",
        event_schema="ev44",
        hist_schema="hs01",
        command_topic="bifrost_jbi_commands",
        response_topic="bifrost_jbi_responses",
        statustopic=["bifrost_jbi_heartbeat"],
        images=[
            "detector_image",
            "detector_tof",
            "psc_monitor",
            "overlap_monitor",
            "bandwidth_monitor",
            "normalization_monitor",
            "elastic_monitor",
        ],
        timers=["timer"],
    ),
    timer=device(
        "nicos_ess.devices.timer.TimerChannel",
        description="Timer",
        fmtstr="%.2f",
        unit="s",
    ),
)

startupcode = """
SetDetectors(jbi_detector)
"""
