description = "15T magnet MAG-001"

pv_root = "SE-MAG-001:"

devices = dict(
    vti_temp=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        description="Regulation temperature",
        readpv=f"{pv_root}VTI-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "K",
                "suffix": "",
                "source_name": f"{pv_root}VTI-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    # vti_temp=device(
    #     "nicos_ess.devices.epics.pva.EpicsNumericReadable",
    #     description="VTI temperature",
    #     readpv=f"{pv_root}VTI-VTITemp-r",
    # ),
    vti_heater_power=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        description="Heater output power",
        readpv=f"{pv_root}VTI-HeaterPower-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "%",
                "suffix": "",
                "source_name": f"{pv_root}VTI-HeaterPower-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    vti_heater_range=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Heater 1 range",
        readpv=f"{pv_root}VTI-HtrRange-s",
        writepv=f"{pv_root}VTI-HtrRange-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "",
                "suffix": "",
                "source_name": f"{pv_root}VTI-HtrRange-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    vti_pressure=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        description="VTI pressure",
        readpv=f"{pv_root}VTI-Pressure-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "mbar",
                "suffix": "",
                "source_name": f"{pv_root}VTI-Pressure-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    vti_pressure_setpoint_percent=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="VTI pressure loop percent setpoint",
        readpv=f"{pv_root}VTI-NVopening-s",
        writepv=f"{pv_root}VTI-NVopening-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "%",
                "suffix": "",
                "source_name": f"{pv_root}VTI-NVopening-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    vti_temp_setpoint=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Temperature setpoint",
        readpv=f"{pv_root}VTI-tempSetpoint-s",
        writepv=f"{pv_root}VTI-tempSetpoint-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "K",
                "suffix": "",
                "source_name": f"{pv_root}VTI-tempSetpoint-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    vti_pressure_setpoint=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="VTI pressure loop setpoint",
        readpv=f"{pv_root}VTI-pressure-s",
        writepv=f"{pv_root}VTI-pressure-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "mbar",
                "suffix": "",
                "source_name": f"{pv_root}VTI-pressure-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    vti_pressure_control=device(
        "nicos_ess.devices.epics.pva.EpicsStringMoveable",
        description="VTI pressure loop control on off. Permitted values: ON, OFF",
        readpv=f"{pv_root}VTI-flowControl-s",
        writepv=f"{pv_root}VTI-flowControl-s",
    ),
    mag_action=device(
        "nicos_ess.devices.epics.pva.EpicsStringMoveable",
        visibility=(),
        description="Action. Permitted values: HOLD, RTOS, RTOZ, CLMP",
        readpv=f"{pv_root}Magnet-action-s",
        writepv=f"{pv_root}Magnet-action-s",
    ),
    mag_switch_heater=device(
        "nicos_ess.devices.epics.pva.EpicsStringMoveable",
        visibility=(),
        description="Set switch heater. Permitted values: ON, OFF",
        readpv=f"{pv_root}Magnet-switchHeater-s",
        writepv=f"{pv_root}Magnet-switchHeater-s",
    ),
    mag_nitrogen_level=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        description="Nitrogen level",
        readpv=f"{pv_root}Magnet-LN2-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-LN2-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_helium_level=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        description="Helium level",
        readpv=f"{pv_root}Magnet-LHe-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-LHe-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_field_setpoint=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        visibility=(),
        description="Magnetic field setpoint",
        readpv=f"{pv_root}Magnet-FieldTarget-s",
        writepv=f"{pv_root}Magnet-FieldTarget-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "T",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-FieldTarget-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_current=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        visibility=(),
        description="mercuryips/current/Z",
        readpv=f"{pv_root}Magnet-Current-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "A",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-Current-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_persistent_field=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        description="Persistent field",
        readpv=f"{pv_root}Magnet-PFLD-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "T",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-PFLD-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_psu_field=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        description="Psu field",
        readpv=f"{pv_root}Magnet-psuField-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "T",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-psuField-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_field_ramp_rate=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        visibility=(),
        description="Magnetic field ramp rate",
        readpv=f"{pv_root}Magnet-fieldRamprate-s",
        writepv=f"{pv_root}Magnet-fieldRamprate-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-fieldRamprate-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_ramp_rate=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        visibility=(),
        description="Ramp rate",
        readpv=f"{pv_root}Magnet-ramprate-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-ramprate-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_mode=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Magnet mode",
        readpv=f"{pv_root}Magnet-Magnet_mode-s",
        writepv=f"{pv_root}Magnet-Magnet_mode-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-Magnet_mode-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_user_field_setpoint=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The magnetic field requested by the user",
        readpv=f"{pv_root}Magnet-UserFieldTarget-s",
        writepv=f"{pv_root}Magnet-UserFieldTarget-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "T",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-UserFieldTarget-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_go=device(
        # bool
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Go",
        readpv=f"{pv_root}Magnet-go-s",
        writepv=f"{pv_root}Magnet-go-s",
    ),
    mag_voltage=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        visibility=(),
        description="Voltage",
        readpv=f"{pv_root}Magnet-voltage-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "V",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-voltage-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        visibility=(),
        description="The status of the instance",
        readpv=f"{pv_root}Magnet-MAG-001status-s",
        writepv=f"{pv_root}Magnet-MAG-001status-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "",
                "suffix": "",
                "source_name": f"{pv_root}Magnet-MAG-001status-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    sample_temp=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        description="Sample temperature",
        readpv=f"{pv_root}Sample-Temp-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "K",
                "suffix": "",
                "source_name": f"{pv_root}Sample-Temp-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    sample_temp_setpoint=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Temperature setpoint",
        readpv=f"{pv_root}Sample-Setpoint-s",
        writepv=f"{pv_root}Sample-Setpoint-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "K",
                "suffix": "",
                "source_name": f"{pv_root}Sample-Setpoint-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    sample_heater_power=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        description="Heater output power",
        readpv=f"{pv_root}Sample-HeaterPower-r",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "",
                "suffix": "",
                "source_name": f"{pv_root}Sample-HeaterPower-r",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    sample_heater_range=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Heater range",
        readpv=f"{pv_root}Sample-HtrRange-s",
        writepv=f"{pv_root}Sample-HtrRange-s",
        nexus_config=[
            {
                "group_name": "magnet_001",
                "nx_class": "NXcollection",
                "units": "",
                "suffix": "",
                "source_name": f"{pv_root}Sample-HtrRange-s",
                "schema": "f144",
                "topic": "bifrost_sample_env",
                "protocol": "pva",
                "periodic": 1,
                "dataset_type": "nx_log",
            },
        ],
    ),
    mag_warning_field_off=device(
        # bool
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="Magnet field off input 1 on moxa",
        readpv=f"{pv_root}warningLights-magnet_field_off-r",
    ),
    mag_warning_interlock=device(
        # bool
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="Connector Interlock detached input 0 on moxa",
        readpv=f"{pv_root}warningLights-connector_interlock-r",
    ),
)
