description = "The choppers for BIFROST"

pv_root_1 = "BIFRO-ChpSy1:Chop-PSC-101:"
pv_root_2 = "BIFRO-ChpSy1:Chop-PSC-102:"
chic_root = "BIFRO-ChpSy1:Chop-CHIC-001:"

devices = dict(
    psc1_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{pv_root_1}ChopState_R",
        visibility=(),
    ),
    psc1_chopper_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv=f"{pv_root_1}C_Execute",
        writepv=f"{pv_root_1}C_Execute",
        requires={"level": "admin"},
        visibility=(),
    ),
    psc1_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{pv_root_1}Spd_R",
        writepv=f"{pv_root_1}Spd_S",
        precision=0.1,
        mapping={
            "0 Hz": 0,
            "14 Hz": 14,
            "28 Hz": 28,
            "42 Hz": 42,
            "56 Hz": 56,
            "70 Hz": 70,
            "84 Hz": 84,
            "98 Hz": 98,
            "112 Hz": 112,
            "126 Hz": 126,
        },
    ),
    psc1_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{pv_root_1}ChopDly-S",
        writepv=f"{pv_root_1}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    psc1_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="psc1_chopper_delay",
        mapped_speed_dev="psc1_chopper_speed",
        offset=0,
        unit="degrees",
    ),
    psc1_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{pv_root_1}DiffTSSamples",
        unit="ns",
        visibility=(
            "metadata",
            "namespace",
        ),
    ),
    psc1_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{pv_root_1}InPhs_R",
    ),
    psc1_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{pv_root_1}Pos_R",
        writepv=f"{pv_root_1}Park_S",
        visibility=(),
    ),
    psc1_chopper_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the PSC1 chopper.",
        readpv=f"{pv_root_1}ParkPos_S",
        writepv=f"{pv_root_1}ParkPos_S",
    ),
    psc1_chopper_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv=f"{chic_root}ConnectedR",
        visibility=(),
        pva=True,
    ),
    psc1_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.ChopperAlarms",
        description="The chopper alarms",
        pv_root=pv_root_1,
        visibility=(),
    ),
    psc1_chopper=device(
        "nicos_ess.devices.epics.chopper.EssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="psc1_chopper_status",
        command="psc1_chopper_control",
        speed="psc1_chopper_speed",
        chic_conn="psc1_chopper_chic",
        alarms="psc1_chopper_alarms",
        slit_edges=[[0, 170.0]],
        resolver_offset=-110.0,
    ),
    psc2_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{pv_root_2}ChopState_R",
        visibility=(),
    ),
    psc2_chopper_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv=f"{pv_root_2}C_Execute",
        writepv=f"{pv_root_2}C_Execute",
        requires={"level": "admin"},
        visibility=(),
    ),
    psc2_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{pv_root_2}Spd_R",
        writepv=f"{pv_root_2}Spd_S",
        precision=0.1,
        mapping={
            "0 Hz": 0,
            "14 Hz": 14,
            "28 Hz": 28,
            "42 Hz": 42,
            "56 Hz": 56,
            "70 Hz": 70,
            "84 Hz": 84,
            "98 Hz": 98,
            "112 Hz": 112,
            "126 Hz": 126,
        },
    ),
    psc2_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{pv_root_2}ChopDly-S",
        writepv=f"{pv_root_2}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    psc2_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="psc2_chopper_delay",
        mapped_speed_dev="psc2_chopper_speed",
        offset=0,
        unit="degrees",
    ),
    psc2_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{pv_root_2}DiffTSSamples",
        unit="ns",
        visibility=(
            "metadata",
            "namespace",
        ),
    ),
    psc2_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{pv_root_2}InPhs_R",
    ),
    psc2_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{pv_root_2}Pos_R",
        writepv=f"{pv_root_2}Park_S",
        visibility=(),
    ),
    psc2_chopper_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the PSC2 chopper.",
        readpv=f"{pv_root_2}ParkPos_S",
        writepv=f"{pv_root_2}ParkPos_S",
    ),
    psc2_chopper_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv=f"{chic_root}ConnectedR",
        visibility=(),
    ),
    psc2_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.ChopperAlarms",
        description="The chopper alarms",
        pv_root=pv_root_2,
        visibility=(),
    ),
    psc2_chopper=device(
        "nicos_ess.devices.epics.chopper.EssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="psc2_chopper_status",
        command="psc2_chopper_control",
        speed="psc2_chopper_speed",
        chic_conn="psc2_chopper_chic",
        alarms="psc2_chopper_alarms",
        slit_edges=[[0.0, 170.0]],
        resolver_offset=-110.0,
    ),
)
