workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG

default:
  tags:
    - docker

variables:
  UV_LINK_MODE: copy

stages:
  - lint
  - test

tests_py312_cov:
  stage: test
  image: registry.esss.lu.se/ecdc/ess-dmsc/docker-almalinux9-conan:1.6.0
  before_script:
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
    - uv sync --extra gui --all-packages
  script:
    - uv run pytest test/ --cov=nicos --cov=nicos_ess --cov-report term --cov-report xml:coverage.xml --junitxml=test-output.xml
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    paths:
      - test-output.xml
      - coverage.xml
    reports:
      junit: test-output.xml
  variables:
    UV_PYTHON: 3.12

tests_py3xx:
  stage: test
  image: registry.esss.lu.se/ecdc/ess-dmsc/docker-almalinux9-conan:1.6.0
  before_script:
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
    - uv sync --extra gui --all-packages
  script:
    - uv run pytest test/ --junitxml=test-output.xml
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.13", "3.14"]
  artifacts:
    paths:
      - test-output.xml
    reports:
      junit: test-output.xml
  variables:
    UV_PYTHON: $PYTHON_VERSION


.lint:
  stage: lint
  image: registry.esss.lu.se/ecdc/ess-dmsc/docker-almalinux9-conan:1.6.0
  before_script:
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
    - uv sync --extra gui --all-packages
    - git fetch --depth 1 origin $CI_MERGE_REQUEST_DIFF_BASE_SHA  # Fetching only up to the closest merge-base to save time
    - export CHANGES=$(git diff-tree --name-only -r $CI_MERGE_REQUEST_DIFF_BASE_SHA $CI_COMMIT_SHA)  # Diff only changed files within MR
    - export PY_CHANGES=$(git diff-tree --name-only -r $CI_MERGE_REQUEST_DIFF_BASE_SHA $CI_COMMIT_SHA | grep -e '\.py$')
  variables:
    UV_PYTHON: 3.12
  allow_failure:
    exit_codes: # User defined exit code
      - 100

lint:check_setups:
  extends:
    - .lint
  script:
    - find ./nicos_ess -type d -name setups -exec uv run tools/check-setups \{\} \;  > >(tee -a check_setups_stdout.log) 2> >(tee -a check_setups_stderr.log >&2)
    - test -z "$(cat check_setups_stdout.log | grep ERROR)" || exit 1 # errors found
    - test ! -f check_setups_stderr.log || exit 1  # failure on check
    - test ! -f check_setups_stdout.log || exit 100 # warnings found

lint:ruff_check:
  extends:
    - .lint
  script:
    - echo 'Changed files (to be linted):'
    - echo "$PY_CHANGES"
    - if [ -z "$PY_CHANGES" ]; then echo "No modified Python files to be checked"; exit 100; fi;
    - uv run ruff check --output-format=gitlab $(echo $PY_CHANGES) | tee code-quality-report.json
  artifacts:
    reports:
      codequality: code-quality-report.json

lint:codespell:
  extends:
    - .lint
  script:
    - echo 'Changed files (to be linted):'
    - echo "$CHANGES"
    - uv run python -m codespell_lib --count $CHANGES

lint:ruff_format:
  extends:
    - .lint
  script:
    - echo 'Changed files (to be linted):'
    - echo "$PY_CHANGES"
    - if [ -z "$PY_CHANGES" ]; then echo "No modified Python files to be checked"; exit 100; fi;
    - uv run ruff format --diff $(echo $PY_CHANGES)
