description = "Selene1 mover motors"

pvprefix = "PSI-ESTIARND:MC-MCU-01:"

devices = dict(
    mover_s1=device(
        "nicos.devices.generic.VirtualMotor",
        # "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="M1 Selene1 1-Mover FL-RE-US",
        # motorpv=f"{pvprefix}m1",
        # has_powerauto=False,
        abslimits=(-1000, 1000),
        unit="deg",
        speed=5,
    ),
    mover_s2=device(
        "nicos.devices.generic.VirtualMotor",
        # "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="M2 Selene1 1-Mover PR-RE-DS",
        # motorpv=f"{pvprefix}m2",
        # has_powerauto=False,
        abslimits=(-1000, 1000),
        unit="deg",
        speed=5,
    ),
    mover_s3=device(
        "nicos.devices.generic.VirtualMotor",
        # "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="M3 Selene1 1-Mover PR-LI-DS",
        # motorpv=f"{pvprefix}m3",
        # has_powerauto=False,
        abslimits=(-1000, 1000),
        unit="deg",
        speed=5,
    ),
    mover_s4=device(
        "nicos.devices.generic.VirtualMotor",
        # "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="M4 Selene1 2-Mover PR-LI-US-1",
        # motorpv=f"{pvprefix}m4",
        # has_powerauto=False,
        abslimits=(-1000, 1000),
        unit="deg",
        speed=5,
    ),
    mover_s5=device(
        "nicos.devices.generic.VirtualMotor",
        # "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="M5 Selene1 2-Mover PR-LI-US-2",
        # motorpv=f"{pvprefix}m5",
        # has_powerauto=False,
        abslimits=(-1000, 1000),
        unit="deg",
        speed=5,
    ),
    mover=device(
        "nicos_ess.estia.devices.mover.SeleneMover",
        description="Selene1 1-Mover",
        s1="mover_s1",
        s2="mover_s2",
        s3="mover_s3",
        s4="mover_s4",
        s5="mover_s5",
    ),
)
