description = (
    "Sample stage system made up of Newport Hexapod "
    "and Goniometer Sample Rotation Stage"
)

hex_root = "ESTIA-SES:MC-MCU-001:"

devices = dict(
    sample_stage_coupling=device(
        "nicos_ess.devices.epics.pva.shutter.EpicsShutter",
        description="Detector Arm Pneumatic Coupling: Support Structure on Air Pads",
        writepv="ESTIA-SpCpl:MC-Pne-01:ShtOpen",
        readpv="ESTIA-SpCpl:MC-Pne-01:ShtAuxBits07",
        statuspv="ESTIA-SpCpl:MC-Pne-01:ShtStatusCode",
        resetpv="ESTIA-SpCpl:MC-Pne-01:ShtErrRst",
        msgtxt="ESTIA-SpCpl:MC-Pne-01:ShtMsgTxt",
        visibility=(),
    ),
    goniometer=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Sample Stage Rotation Base",
        motorpv="ESTIA-SpRot:MC-RotZ01:Mtr",
        has_powerauto=False,
        fmtstr="%.2f",
    ),
    tx=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Tx Translation",
        motorpv=f"{hex_root}m1",
        has_powerauto=False,
        has_reseterror=False,
        has_errorbit=False,
        has_msgtxt=False,
        fmtstr="%.2f",
        visibility=(),
    ),
    ty=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Ty Translation",
        motorpv=f"{hex_root}m2",
        has_powerauto=False,
        has_reseterror=False,
        has_errorbit=False,
        has_msgtxt=False,
        fmtstr="%.2f",
        visibility=(),
    ),
    tz=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Tz Translation",
        motorpv=f"{hex_root}m3",
        has_powerauto=False,
        has_reseterror=False,
        has_errorbit=False,
        has_msgtxt=False,
        fmtstr="%.2f",
        visibility=(),
    ),
    rx=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Rx Rotation",
        motorpv=f"{hex_root}m4",
        has_powerauto=False,
        has_reseterror=False,
        has_errorbit=False,
        has_msgtxt=False,
        fmtstr="%.2f",
        visibility=(),
    ),
    ry=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Ry Rotation",
        motorpv=f"{hex_root}m5",
        has_powerauto=False,
        has_reseterror=False,
        has_errorbit=False,
        has_msgtxt=False,
        fmtstr="%.2f",
        visibility=(),
    ),
    rz=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Rz Rotation",
        motorpv=f"{hex_root}m6",
        has_powerauto=False,
        has_reseterror=False,
        has_errorbit=False,
        has_msgtxt=False,
        fmtstr="%.2f",
        visibility=(),
    ),
    estia_hexapod=device(
        "nicos_ess.estia.devices.newport.NewportHexapod",
        description="Hexapod Device",
        tx="tx",
        ty="ty",
        tz="tz",
        rx="rx",
        ry="ry",
        rz="rz",
        gmt="goniometer",
        tx_sp="setpoint_1",
        ty_sp="setpoint_2",
        tz_sp="setpoint_3",
        rx_sp="setpoint_4",
        ry_sp="setpoint_5",
        rz_sp="setpoint_6",
        status="hexapod_status",
        errmsg="hexapod_error_msg",
        move_all="move_all_control",
    ),
    hexapod_status=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="NewPort Status",
        readpv=f"{hex_root}STATUS",
        visibility=(),
    ),
    hexapod_error_msg=device(
        "nicos_ess.devices.epics.pva.EpicsStringReadable",
        description="NewPort Status",
        readpv=f"{hex_root}ERR_DESC",
        visibility=(),
    ),
    hexapod_coord_mode=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Current coordinate system",
        readpv=f"{hex_root}CS",
        writepv=f"{hex_root}CS",
    ),
    # SETPOINTS FOR HEXAPOD
    setpoint_1=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Moveall setpoint",
        readpv=f"{hex_root}T1",
        writepv=f"{hex_root}T1",
        visibility=(),
    ),
    setpoint_2=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Moveall setpoint",
        readpv=f"{hex_root}T2",
        writepv=f"{hex_root}T2",
        visibility=(),
    ),
    setpoint_3=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Moveall setpoint",
        readpv=f"{hex_root}T3",
        writepv=f"{hex_root}T3",
        visibility=(),
    ),
    setpoint_4=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Moveall setpoint",
        readpv=f"{hex_root}T4",
        writepv=f"{hex_root}T4",
        visibility=(),
    ),
    setpoint_5=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Moveall setpoint",
        readpv=f"{hex_root}T5",
        writepv=f"{hex_root}T5",
        visibility=(),
    ),
    setpoint_6=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Moveall setpoint",
        readpv=f"{hex_root}T6",
        writepv=f"{hex_root}T6",
        visibility=(),
    ),
    move_all_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The move all commander for the hexapod",
        readpv=f"{hex_root}MOVE_ALL",
        writepv=f"{hex_root}MOVE_ALL",
        visibility=(),
    ),
)
