description = "Motors for Driver1"

# pvprefix = "ESTIA-SG1Rb:MC"
pvprefix = "IOC:"

devices = dict(
    robot_pos=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="I don't know",
        motorpv=f"{pvprefix}m5",
        # motorpv=f"{pvprefix}-LinY-01:Mtr",
        # powerautopv=f"{pvprefix}-LinY-01:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-LinY-01:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-LinY-01:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-LinY-01:Mtr-ErrRst",
        # temppv=f"{pvprefix}-LinY-01:Mtr-Temp",
        unit="mm",
        abslimits=(0, 25),
        userlimits=(0, 25),
    ),
    robot_vert=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="I don't know even more",
        motorpv=f"{pvprefix}m6",
        # motorpv=f"{pvprefix}-LinY-01:Mtr",
        # powerautopv=f"{pvprefix}-LinY-01:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-LinY-01:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-LinY-01:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-LinY-01:Mtr-ErrRst",
        # temppv=f"{pvprefix}-LinY-01:Mtr-Temp",
        unit="mm",
        abslimits=(0, 25),
        userlimits=(0, 25),
    ),
    driver1_1_adjust=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Driver1-1 Adjust",
        motorpv=f"{pvprefix}m2",
        # motorpv=f"{pvprefix}-RotY-01:Mtr",
        # powerautopv=f"{pvprefix}-RotY-01:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-RotY-01:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-RotY-01:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-RotY-01:Mtr-ErrRst",
        # temppv=f"{pvprefix}-RotY-01:Mtr-Temp",
        unit="mm",
        abslimits=(0, 360),
        userlimits=(0, 360),
    ),
    driver1_1_approach=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Driver1-1 Approach",
        motorpv=f"{pvprefix}m1",
        # motorpv=f"{pvprefix}-LinY-01:Mtr",
        # powerautopv=f"{pvprefix}-LinY-01:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-LinY-01:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-LinY-01:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-LinY-01:Mtr-ErrRst",
        # temppv=f"{pvprefix}-LinY-01:Mtr-Temp",
        unit="mm",
        abslimits=(0, 25),
        userlimits=(0, 25),
    ),
    # driver1_1_hex_state=device(
    #     "nicos_ess.devices.epics.pva.EpicsMappedReadable",
    #     description="Hexscrew state",
    #     readpv=f"{pvprefix}Mtr8-HexScrew",
    # ),
    driver1_2_adjust=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Driver1-2 Adjust",
        motorpv=f"{pvprefix}m4",
        # motorpv=f"{pvprefix}-RotY-01:Mtr",
        # powerautopv=f"{pvprefix}-RotY-01:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-RotY-01:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-RotY-01:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-RotY-01:Mtr-ErrRst",
        # temppv=f"{pvprefix}-RotY-01:Mtr-Temp",
        unit="mm",
        abslimits=(0, 360),
        userlimits=(0, 360),
    ),
    driver1_2_approach=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Driver1-2 Approach",
        motorpv=f"{pvprefix}m3",
        # motorpv=f"{pvprefix}-LinY-02:Mtr",
        # powerautopv=f"{pvprefix}-LinY-02:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-LinY-02:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-LinY-02:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-LinY-02:Mtr-ErrRst",
        # temppv=f"{pvprefix}-LinY-02:Mtr-Temp",
        unit="mm",
        abslimits=(0, 25),
        userlimits=(0, 25),
    ),
    # driver1_2_hex_state=device(
    #     "nicos_ess.devices.epics.pva.EpicsMappedReadable",
    #     description="Hexscrew state",
    #     readpv=f"{pvprefix}Mtr9-HexScrew",
    # ),
)
