description = "Motors for Driver1"

# pvprefix = "ESTIA-SG1Rb:MC"
pvprefix = "IOC:"

devices = dict(
    robot_pos=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="I don't know",
        motorpv=f"{pvprefix}m5",
        # motorpv=f"{pvprefix}-LinY-01:Mtr",
        # powerautopv=f"{pvprefix}-LinY-01:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-LinY-01:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-LinY-01:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-LinY-01:Mtr-ErrRst",
        # temppv=f"{pvprefix}-LinY-01:Mtr-Temp",
        unit="mm",
        abslimits=(0, 25),
        userlimits=(0, 25),
    ),
    robot_vert=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="I don't know even more",
        motorpv=f"{pvprefix}m6",
        # motorpv=f"{pvprefix}-LinY-01:Mtr",
        # powerautopv=f"{pvprefix}-LinY-01:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-LinY-01:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-LinY-01:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-LinY-01:Mtr-ErrRst",
        # temppv=f"{pvprefix}-LinY-01:Mtr-Temp",
        unit="mm",
        abslimits=(0, 25),
        userlimits=(0, 25),
    ),
    driver1_1_adjust=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Driver1-1 Adjust",
        motorpv=f"{pvprefix}m2",
        # motorpv=f"{pvprefix}-RotY-01:Mtr",
        # powerautopv=f"{pvprefix}-RotY-01:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-RotY-01:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-RotY-01:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-RotY-01:Mtr-ErrRst",
        # temppv=f"{pvprefix}-RotY-01:Mtr-Temp",
        unit="mm",
        abslimits=(0, 360),
        userlimits=(0, 360),
    ),
    driver1_1_approach=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Driver1-1 Approach",
        motorpv=f"{pvprefix}m1",
        # motorpv=f"{pvprefix}-LinY-01:Mtr",
        # powerautopv=f"{pvprefix}-LinY-01:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-LinY-01:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-LinY-01:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-LinY-01:Mtr-ErrRst",
        # temppv=f"{pvprefix}-LinY-01:Mtr-Temp",
        unit="mm",
        abslimits=(0, 25),
        userlimits=(0, 25),
    ),
    driver1_1_hex_state=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="Hexscrew state",
        readpv="TEST:UNKNOWN-22:Labels",
    ),
    driver1_2_adjust=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Driver1-2 Adjust",
        motorpv=f"{pvprefix}m4",
        # motorpv=f"{pvprefix}-RotY-01:Mtr",
        # powerautopv=f"{pvprefix}-RotY-01:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-RotY-01:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-RotY-01:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-RotY-01:Mtr-ErrRst",
        # temppv=f"{pvprefix}-RotY-01:Mtr-Temp",
        unit="mm",
        abslimits=(0, 360),
        userlimits=(0, 360),
    ),
    driver1_2_approach=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Driver1-2 Approach",
        motorpv=f"{pvprefix}m3",
        # motorpv=f"{pvprefix}-LinY-02:Mtr",
        # powerautopv=f"{pvprefix}-LinY-02:Mtr-PwrAuto",
        # errormsgpv=f"{pvprefix}-LinY-02:Mtr-MsgTxt",
        # errorbitpv=f"{pvprefix}-LinY-02:Mtr-Err",
        # reseterrorpv=f"{pvprefix}-LinY-02:Mtr-ErrRst",
        # temppv=f"{pvprefix}-LinY-02:Mtr-Temp",
        unit="mm",
        abslimits=(0, 25),
        userlimits=(0, 25),
    ),
    driver1_2_hex_state=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="Hexscrew state",
        readpv="TEST:UNKNOWN-22:Labels",
    ),
    sr1=device(
        "nicos_ess.estia.devices.selene.SeleneRobot",
        description="Selene robot 1",
        move_x="robot_pos",
        move_z="robot_vert",
        adjust1="driver1_1_adjust",
        approach1="driver1_1_approach",
        hex_state1="driver1_1_hex_state",
        adjust2="driver1_2_adjust",
        approach2="driver1_2_approach",
        hex_state2="driver1_2_hex_state",
        delta12=5,
        engaged=5,
        retracted=5,
        position_data="its not used",
        positions={
            1: {
                1: (50, 234),
            },
            2: {
                2: (50, 64),
            },
            3: {
                3: (50, 30),
            },
            4: {
                4: (445, 234),
            },
            5: {
                5: (445, 128),
            },
            6: {
                6: (445, 64),
            },
            # :second guide, not active
            7: {
                7: (50, 500 - 128),
            },
            8: {
                8: (50, 500 - 64),
            },
            9: {
                9: (50, 500 - 30),
            },
            10: {
                10: (445, 500 - 234),
            },
            11: {
                11: (445, 500 - 128),
            },
            12: {
                12: (445, 500 - 64),
            },
        },
    ),
)
