description = "Deformation Rig MEC-002"

pv_root = "SE-MEC2:SE-DefRig-001:"

devices = dict(
    rig_motor_power=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Motor Power ON/OFF",
        readpv="{}MotorPowerOn-RB".format(pv_root),
        writepv="{}MotorPowerOn-SP".format(pv_root),
    ),
    rig_motor_run=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Motor running / not running",
        readpv="{}MotorRun-RB".format(pv_root),
        writepv="{}MotorRun-SP".format(pv_root),
    ),
    rig_motor_speed=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Speed of motor",
        readpv="{}MotorSpeed-RB".format(pv_root),
        writepv="{}MotorSpeed-SP".format(pv_root),
        targetpv="{}MotorSpeed-SP".format(pv_root),
    ),
    rig_motor_direction=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Motor direction",
        readpv="{}MotorDirection-RB".format(pv_root),
        writepv="{}MotorDirection-SP".format(pv_root),
    ),
    rig_load_highlimit=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Load high limit",
        readpv="{}LoadHighLimit-RB".format(pv_root),
        writepv="{}LoadHighLimit-SP".format(pv_root),
        targetpv="{}LoadHighLimit-SP".format(pv_root),
    ),
    rig_load_lowlimit=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Load low limit",
        readpv="{}LoadLowLimit-RB".format(pv_root),
        writepv="{}LoadLowLimit-SP".format(pv_root),
        targetpv="{}LoadLowLimit-SP".format(pv_root),
    ),
    rig_load_sensor=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="Load sensor readout",
        readpv="{}LoadValue-Mon".format(pv_root),
    ),
    rig_stroke_sensor=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="Stroke reading after conversion",
        readpv="{}StrokeValue-Mon".format(pv_root),
    ),
    rig_stroke_conversion_factor=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Conversion factor to Newton",
        readpv="{}StrokeConversion-RB".format(pv_root),
        writepv="{}StrokeConversion-SP".format(pv_root),
        targetpv="{}StrokeConversion-SP".format(pv_root),
    ),
    rig_stroke_eccentric=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke eccentric, zeroing value",
        readpv="{}StrokeEccentric-RB".format(pv_root),
        writepv="{}StrokeEccentric-SP".format(pv_root),
        targetpv="{}StrokeEccentric-SP".format(pv_root),
    ),
    rig_stroke_gain=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke gain",
        readpv="{}StrokeGain-RB".format(pv_root),
        writepv="{}StrokeGain-SP".format(pv_root),
        targetpv="{}StrokeGain-SP".format(pv_root),
    ),
    rig_stroke_highlimit=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke high limit",
        readpv="{}StrokeHighLimit-RB".format(pv_root),
        writepv="{}StrokeHighLimit-SP".format(pv_root),
        targetpv="{}StrokeHighLimit-SP".format(pv_root),
    ),
    rig_stroke_lowlimit=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke low limit",
        readpv="{}StrokeLowLimit-RB".format(pv_root),
        writepv="{}StrokeLowLimit-SP".format(pv_root),
        targetpv="{}StrokeLowLimit-SP".format(pv_root),
    ),
    rig_turbine_meter=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Turbine meter signal",
        readpv="{}TurbineMeter-Mon".format(pv_root),
        writepv="{}TurbineMeter-Mon".format(pv_root),
    ),
    rig_turbine_meter_readout=device(
        "nicos_ess.devices.epics.pva.EpicsStringReadable",
        description="Signal coming from cooling water flow",
        readpv="{}CoolingTurbine-Mon".format(pv_root),
    ),
    rig_cooling_valve=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Cooling valve state",
        readpv="{}CoolingValveOpen-RB".format(pv_root),
        writepv="{}CoolingValveOpen-SP".format(pv_root),
    ),
    rig_flush_valve=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Flush valve state",
        readpv="{}FlushValveOpen-RB".format(pv_root),
        writepv="{}FlushValveOpen-SP".format(pv_root),
    ),
    rig_load_conversion_factor=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Conversion factor to Newton",
        readpv="{}LoadConversion-RB".format(pv_root),
        writepv="{}LoadConversion-SP".format(pv_root),
        targetpv="{}LoadConversion-SP".format(pv_root),
    ),
    rig_load_eccentric=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Load eccentric, zeroing value",
        readpv="{}LoadEccentric-RB".format(pv_root),
        writepv="{}LoadEccentric-SP".format(pv_root),
        targetpv="{}LoadEccentric-SP".format(pv_root),
    ),
    rig_load_gain=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Load gain",
        readpv="{}LoadGain-RB".format(pv_root),
        writepv="{}LoadGain-SP".format(pv_root),
        targetpv="{}LoadGain-SP".format(pv_root),
    ),
    rig_PID_compression_setpoint=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke low limit",
        readpv="{}PidSetpoint1-RB".format(pv_root),
        writepv="{}PidSetpoint1-SP".format(pv_root),
        targetpv="{}PidSetpoint1-SP".format(pv_root),
    ),
    rig_PID_tension_setpoint=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke low limit",
        readpv="{}PidSetpoint2-RB".format(pv_root),
        writepv="{}PidSetpoint2-SP".format(pv_root),
        targetpv="{}PidSetpoint2-SP".format(pv_root),
    ),
    rig_PID_activation=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="PID state",
        readpv="{}PidActivate-RB".format(pv_root),
        writepv="{}PidActivate-SP".format(pv_root),
    ),
    rig_PID_control_type=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="PID control type",
        readpv="{}ControlType-RB".format(pv_root),
        writepv="{}ControlType-SP".format(pv_root),
    ),
    rig_PID_parameter_1=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="PID parameter 1",
        readpv="{}PidParam1-RB".format(pv_root),
        writepv="{}PidParam1-SP".format(pv_root),
        targetpv="{}PidParam1-SP".format(pv_root),
    ),
    rig_PID_parameter_2=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="PID parameter 2",
        readpv="{}PidParam2-RB".format(pv_root),
        writepv="{}PidParam2-SP".format(pv_root),
        targetpv="{}PidParam2-SP".format(pv_root),
    ),
    rig_PID_parameter_3=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="PID parameter 3",
        readpv="{}PidParam3-RB".format(pv_root),
        writepv="{}PidParam3-SP".format(pv_root),
        targetpv="{}PidParam3-SP".format(pv_root),
    ),
    rig_profile_mode=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Preset profile",
        readpv="{}ProgramActivate-RB".format(pv_root),
        writepv="{}ProgramActivate-SP".format(pv_root),
    ),
)
