description = "Deformation Rig MEC-002"

pv_root = "SE-MEC2:SE-DefRig-001:"

devices = dict(
    rig_motor_power=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Motor Power ON/OFF",
        readpv=f"{pv_root}MotorPowerOn-RB",
        writepv=f"{pv_root}MotorPowerOn-SP",
    ),
    rig_motor_run=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Motor running / not running",
        readpv=f"{pv_root}MotorRun-RB",
        writepv=f"{pv_root}MotorRun-SP",
    ),
    rig_motor_speed=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Speed of motor",
        readpv=f"{pv_root}MotorSpeed-RB",
        writepv=f"{pv_root}MotorSpeed-SP",
        targetpv=f"{pv_root}MotorSpeed-SP",
    ),
    rig_motor_direction=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Motor direction",
        readpv=f"{pv_root}MotorDirection-RB",
        writepv=f"{pv_root}MotorDirection-SP",
    ),
    rig_load_highlimit=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Load high limit",
        readpv=f"{pv_root}LoadHighLimit-RB",
        writepv=f"{pv_root}LoadHighLimit-SP",
        targetpv=f"{pv_root}LoadHighLimit-SP",
    ),
    rig_load_lowlimit=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Load low limit",
        readpv=f"{pv_root}LoadLowLimit-RB",
        writepv=f"{pv_root}LoadLowLimit-SP",
        targetpv=f"{pv_root}LoadLowLimit-SP",
    ),
    rig_load_limit_control=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="Move load high and low limit to selected values",
        readpv=f"{pv_root}LoadSetpoint-Cmd",
        writepv=f"{pv_root}LoadSetpoint-Cmd",
        mapping={"Set values": 1},
    ),
    rig_load_sensor=device(
        "nicos_ess.devices.epics.pva.EpicsNumericReadable",
        description="Load sensor readout",
        readpv=f"{pv_root}LoadValue-Mon",
        fmtstr="%.6f",
    ),
    rig_stroke_sensor=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="Stroke reading after conversion",
        readpv=f"{pv_root}StrokeValue-Mon",
        fmtstr="%.6f",
    ),
    rig_stroke_conversion_factor=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Conversion factor to Newton",
        readpv=f"{pv_root}StrokeConversion-RB",
        writepv=f"{pv_root}StrokeConversion-SP",
        targetpv=f"{pv_root}StrokeConversion-SP",
    ),
    rig_stroke_eccentric=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke eccentric, zeroing value",
        readpv=f"{pv_root}StrokeEccentric-RB",
        writepv=f"{pv_root}StrokeEccentric-SP",
        targetpv=f"{pv_root}StrokeEccentric-SP",
    ),
    rig_stroke_gain=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke gain",
        readpv=f"{pv_root}StrokeGain-RB",
        writepv=f"{pv_root}StrokeGain-SP",
        targetpv=f"{pv_root}StrokeGain-SP",
    ),
    rig_stroke_highlimit=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke high limit",
        readpv=f"{pv_root}StrokeHighLimit-RB",
        writepv=f"{pv_root}StrokeHighLimit-SP",
        targetpv=f"{pv_root}StrokeHighLimit-SP",
    ),
    rig_stroke_lowlimit=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke low limit",
        readpv=f"{pv_root}StrokeLowLimit-RB",
        writepv=f"{pv_root}StrokeLowLimit-SP",
        targetpv=f"{pv_root}StrokeLowLimit-SP",
    ),
    rig_stroke_limit_control=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="Move stroke high and low limit to selected values",
        readpv=f"{pv_root}StrokeSetpoint-Cmd",
        writepv=f"{pv_root}StrokeSetpoint-Cmd",
        mapping={"Set values": 1},
    ),
    rig_turbine_meter=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Turbine meter signal",
        readpv=f"{pv_root}TurbineMeter-Mon",
        writepv=f"{pv_root}TurbineMeter-Mon",
    ),
    rig_turbine_meter_readout=device(
        "nicos_ess.devices.epics.pva.EpicsStringReadable",
        description="Signal coming from cooling water flow",
        readpv=f"{pv_root}CoolingTurbine-Mon",
    ),
    rig_cooling_valve=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Cooling valve state",
        readpv=f"{pv_root}CoolingValveOpen-RB",
        writepv=f"{pv_root}CoolingValveOpen-SP",
    ),
    rig_flush_valve=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Flush valve state",
        readpv=f"{pv_root}FlushValveOpen-RB",
        writepv=f"{pv_root}FlushValveOpen-SP",
    ),
    rig_load_conversion_factor=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Conversion factor to Newton",
        readpv=f"{pv_root}LoadConversion-RB",
        writepv=f"{pv_root}LoadConversion-SP",
        targetpv=f"{pv_root}LoadConversion-SP",
    ),
    rig_load_eccentric=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Load eccentric, zeroing value",
        readpv=f"{pv_root}LoadEccentric-RB",
        writepv=f"{pv_root}LoadEccentric-SP",
        targetpv=f"{pv_root}LoadEccentric-SP",
    ),
    rig_load_gain=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Load gain",
        readpv=f"{pv_root}LoadGain-RB",
        writepv=f"{pv_root}LoadGain-SP",
        targetpv=f"{pv_root}LoadGain-SP",
    ),
    rig_PID_compression_setpoint=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke low limit",
        readpv=f"{pv_root}PidSetpoint1-RB",
        writepv=f"{pv_root}PidSetpoint1-SP",
        targetpv=f"{pv_root}PidSetpoint1-SP",
    ),
    rig_PID_tension_setpoint=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="Stroke low limit",
        readpv=f"{pv_root}PidSetpoint2-RB",
        writepv=f"{pv_root}PidSetpoint2-SP",
        targetpv=f"{pv_root}PidSetpoint2-SP",
    ),
    rig_PID_activation=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="PID state",
        readpv=f"{pv_root}PidActivate-RB",
        writepv=f"{pv_root}PidActivate-SP",
    ),
    rig_PID_control_type=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="PID control type",
        readpv=f"{pv_root}ControlType-RB",
        writepv=f"{pv_root}ControlType-SP",
    ),
    rig_PID_parameter_P=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="PID parameter P",
        readpv=f"{pv_root}PidParam1-RB",
        writepv=f"{pv_root}PidParam1-SP",
        targetpv=f"{pv_root}PidParam1-SP",
    ),
    rig_PID_parameter_I=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="PID parameter I",
        readpv=f"{pv_root}PidParam2-RB",
        writepv=f"{pv_root}PidParam2-SP",
        targetpv=f"{pv_root}PidParam2-SP",
    ),
    rig_PID_parameter_D=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="PID parameter D",
        readpv=f"{pv_root}PidParam3-RB",
        writepv=f"{pv_root}PidParam3-SP",
        targetpv=f"{pv_root}PidParam3-SP",
    ),
    rig_PID_control=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="Move PID parameters to selected values",
        readpv=f"{pv_root}PidParam-Cmd",
        writepv=f"{pv_root}PidParam-Cmd",
        mapping={"Set values": 1},
    ),
    rig_profile_mode=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Preset profile",
        readpv=f"{pv_root}ProgramActivate-RB",
        writepv=f"{pv_root}ProgramActivate-SP",
    ),
)
