# ruff: noqa: F821
description = "JustBinIt histogrammer."

devices = dict(
    det_fw_endcap=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="Detector bank FW Endcap just-bin-it image channel",
        hist_topic="dream_visualisation",
        data_topic="dream_detector_fwec",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=280,
        det_height=256,
        det_range=(1, 71680),
    ),
    det_bw_endcap=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="Detector bank BW Endcap just-bin-it image channel",
        hist_topic="dream_visualisation",
        data_topic="dream_detector_bwec",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=616,
        det_height=256,
        det_range=(71680, 229376),
    ),
    det_mantle=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="Detector bank mantle just-bin-it image channel",
        hist_topic="dream_visualisation",
        data_topic="dream_detector_mantle",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=256,
        det_height=1920,
        det_range=(229377, 720896),
    ),
    det_sans=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="Detector bank SANS just-bin-it image channel",
        hist_topic="dream_visualisation",
        data_topic="dream_detector_sans",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=112,
        det_height=3584,
        det_range=(720897, 1122304),
    ),
    det_high_resolution=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="Detector bank high resolution just-bin-it image channel",
        hist_topic="dream_visualisation",
        data_topic="dream_detector_hr",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=112,
        det_height=3584,
        det_range=(1122305, 1523712),
    ),
    jbi_detector=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItDetector",
        description="Just Bin it histogrammer",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="",
        event_schema="ev44",
        hist_schema="hs01",
        command_topic="dream_jbi_commands",
        response_topic="dream_jbi_responses",
        statustopic=["dream_jbi_heartbeat"],
        images=[
            "det_fw_endcap", 
            "det_bw_endcap",
            "det_mantle",
            "det_sans",
            "det_high_resolution",
        ],
        timers=["timer"],
    ),
    timer=device(
        "nicos_ess.devices.timer.TimerChannel",
        description="Timer",
        fmtstr="%.2f",
        unit="s",
    ),
)

startupcode = """
SetDetectors(jbi_detector)
"""
