description = "The livedata interface for dream."

devices = dict(
    monitor_bunker_counts_total=device(
        "nicos_ess.devices.datasources.livedata.DataChannel",
        description="Livedata channel 1",
        device_name="monitor_bunker_counts_total",
        workflow_id="dream/monitor_histogram/1",
        type="counter",
    ),
    monitor_cave_counts_total=device(
        "nicos_ess.devices.datasources.livedata.DataChannel",
        description="Livedata channel 2",
        device_name="monitor_cave_counts_total",
        workflow_id="dream/monitor_histogram/1",
        type="counter",
    ),
    mantle_detector_counts_total=device(
        "nicos_ess.devices.datasources.livedata.DataChannel",
        description="Livedata channel 3",
        device_name="mantle_detector_counts_total",
        workflow_id="dream/detector_projection/1",
        type="counter",
    ),
    endcap_backward_detector_counts_total=device(
        "nicos_ess.devices.datasources.livedata.DataChannel",
        description="Livedata channel 4",
        device_name="endcap_backward_detector_counts_total",
        workflow_id="dream/detector_projection/1",
        type="counter",
    ),
    endcap_forward_detector_counts_total=device(
        "nicos_ess.devices.datasources.livedata.DataChannel",
        description="Livedata channel 5",
        device_name="endcap_forward_detector_counts_total",
        workflow_id="dream/detector_projection/1",
        type="counter",
    ),
    high_resolution_detector_counts_total=device(
        "nicos_ess.devices.datasources.livedata.DataChannel",
        description="Livedata channel 6",
        device_name="high_resolution_detector_counts_total",
        workflow_id="dream/detector_projection/1",
        type="counter",
    ),
    sans_detector_counts_total=device(
        "nicos_ess.devices.datasources.livedata.DataChannel",
        description="Livedata channel 7",
        device_name="sans_detector_counts_total",
        workflow_id="dream/detector_projection/1",
        type="counter",
    ),
    livedata_collector=device(
        "nicos_ess.devices.datasources.livedata.LiveDataCollector",
        description="The livedata detector collector",
        brokers=configdata("config.KAFKA_BROKERS"),
        data_topics=["dream_livedata_data"],
        status_topics=["dream_livedata_heartbeat"],
        commands_topic="dream_livedata_commands",
        others=[
            "monitor_bunker_counts_total",
            "monitor_cave_counts_total",
            "mantle_detector_counts_total",
            "endcap_backward_detector_counts_total",
            "endcap_forward_detector_counts_total",
            "high_resolution_detector_counts_total",
            "sans_detector_counts_total",
        ],
    ),
)
