collimator_map = {
    "L,N,N": (144.14, 65, 80),
    "L,N,1": (144.14, 65, 35),
    "L,N,3": (144.14, 65, 0),
    "L,S,N": (144.14, 6, 80),
    "L,S,1": (144.14, 6, 35),
    "L,S,3": (144.14, 6, 0),
    "3,N,1": (74.14, 100, 104.8),
    "3,N,3": (74.14, 100, 69.8),
    "3,N,5": (74.14, 100, 34.8),
    "3,N,10": (74.14, 100, 0),
    "3,S,1": (74.14, 76, 104.8),
    "3,S,3": (74.14, 76, 69.8),
    "3,S,5": (74.14, 76, 34.8),
    "3,S,10": (74.14, 76, 0),
    "3,M,1": (74.14, 36, 104.8),
    "3,M,3": (74.14, 36, 69.8),
    "3,M,5": (74.14, 36, 34.8),
    "3,M,10": (74.14, 36, 0),
    "3,L,1": (74.14, 3, 104.8),
    "3,L,3": (74.14, 3, 69.8),
    "3,L,5": (74.14, 3, 34.8),
    "3,L,10": (74.14, 3, 0),
    "10,M,5": (4.14, 103, 105.1),
    "10,M,1": (4.14, 103, 70.1),
    "10,M,N": (4.14, 103, 0),
    "10,L,5": (4.14, 66, 105.1),
    "10,L,1": (4.14, 66, 70.1),
    "10,L,N": (4.14, 66, 0),
    "10,N,5": (4.14, 0, 105.1),
    "10,N,1": (4.14, 0, 70.1),
    "10,N,N": (4.14, 0, 0),
}

devices = dict(
    axis_attenuator_changer=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Attenuator changer",
        motorpv="TBL-AttChg:MC-LinY-01:Mtr",
        monitor_deadband=0.01,
    ),
    axis_attenuator_changer_temp=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="Attenuator changer temperature",
        readpv="TBL-AttChg:MC-LinY-01:Mtr-Temp",
    ),
    axis_horizontal=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Collimator horizontal",
        motorpv="TBL-PinLin:MC-LinY-01:Mtr",
        monitor_deadband=0.01,
    ),
    axis_horizontal_temp=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="Collimator horizontal temperature",
        readpv="TBL-PinLin:MC-LinY-01:Mtr-Temp",
    ),
    axis_vertical=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Collimator horizontal",
        motorpv="TBL-PinLif:MC-LinZ-01:Mtr",
        monitor_deadband=0.01,
    ),
    axis_vertical_temp=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="Collimator vertical temperature",
        readpv="TBL-PinLif:MC-LinZ-01:Mtr-Temp",
    ),
    axis_pinhole_changer=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Pinhole changer",
        motorpv="TBL-PinChg:MC-LinY-01:Mtr",
        monitor_deadband=0.01,
    ),
    axis_pinhole_changer_temp=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="Pinhole changer temperature",
        readpv="TBL-PinChg:MC-LinY-01:Mtr-Temp",
    ),
    config_set=device(
        "nicos_ess.devices.mapped_controller.MultiTargetMapping",
        controlled_devices=[
            "axis_horizontal",
            "axis_attenuator_changer",
            "axis_pinhole_changer",
        ],
        mapping=collimator_map,
    ),
    mapping_composer=device(
        "nicos_ess.devices.mapped_controller.MultiTargetComposer",
        out="config_set",
        visibility=(),
    ),
    config_collimator=device(
        "nicos_ess.devices.mapped_controller.MultiTargetSelector",
        composer="mapping_composer",
        idx=0,
        mapping={
            "Large collimator": "L",
            "3 mm collimator": "3",
            "10 mm collimator": "10",
        },
    ),
    config_attenuator=device(
        "nicos_ess.devices.mapped_controller.MultiTargetSelector",
        composer="mapping_composer",
        idx=1,
        mapping={
            "No attenuator": "N",
            "Small attenuator": "S",
            "Medium attenuator": "M",
            "Large attenuator": "L",
        },
    ),
    config_pinhole=device(
        "nicos_ess.devices.mapped_controller.MultiTargetSelector",
        composer="mapping_composer",
        idx=2,
        mapping={
            "No pinhole": "N",
            "1 mm pinhole": "1",
            "3 mm pinhole": "3",
            "5 mm pinhole": "5",
            "10 mm pinhole": "10",
        },
    ),
)
