description = "The just-bin-it histogrammer."

devices = dict(
    jbi_detector=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItDetector",
        description="The just-bin-it histogrammer",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="",
        event_schema="ev44",
        hist_schema="hs01",
        liveinterval=1,
        command_topic="tbl_jbi_commands",
        response_topic="tbl_jbi_responses",
        statustopic=["tbl_jbi_heartbeat"],
        images=[
            "mb_det",
            "he3_det_1",
            "he3_det_2",
            "tpx3_det",
            "ngem_det",
        ],
        timers=["timer"],
        counters=["pulse_counter"],
    ),
    timer=device(
        "nicos_ess.devices.timer.TimerChannel",
        description="Timer",
        fmtstr="%.2f",
        unit="s",
    ),
    pulse_counter=device(
        "nicos_ess.devices.epics.pulse_counter.PulseCounter",
        description="EVR Pulse Counter",
        readpv="TBL-DtCmn:Ctrl-EVR-001:EvtHCnt-I",
        fmtstr="%d",
    ),
    mb_det=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="tbl_visualisation",
        data_topic="tbl_detector_mb",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=64,
        det_height=448,
        det_range=(1, 28672),
    ),
    he3_det_1=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="tbl_visualisation",
        data_topic="tbl_detector_3he",
        source="bank0",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=100,
        det_height=4,
        det_range=(1, 400),
    ),
    he3_det_2=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="tbl_visualisation",
        data_topic="tbl_detector_3he",
        source="bank1",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=100,
        det_height=4,
        det_range=(401, 800),
    ),
    tpx3_det=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="Timepix 3 just-bin-it channel",
        hist_topic="tbl_visualisation",
        data_topic="tbl_detector_tpx3_empir",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=4096,
        det_height=4096,
        det_range=(1, 16777216),
    ),
    ngem_det=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="Timepix 3 just-bin-it channel",
        hist_topic="tbl_visualisation",
        data_topic="tbl_detector_ngem",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=128,
        det_height=128,
        det_range=(1, 16384),
    ),
)
