description = "Motion cabinet 4"

devices = dict(
    cabinet_4_status=device(
        "nicos_ess.devices.epics.mbbi_direct.MBBIDirectStatus",
        description="Cabinet 4 status",
        pv_root="TBL-MCS4:MC-MCU-04:Cabinet",
        number_of_bits=24,
    ),
    cabinet_4_pressure_1=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="Cabinet 4 pressure 1",
        readpv="TBL-MCS4:MC-MCU-04:Pressure1",
    ),
    cabinet_4_pressure_2=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="Cabinet 4 pressure 2",
        readpv="TBL-MCS4:MC-MCU-04:Pressure2",
    ),
    mc_pne_415=device(
        "nicos_ess.devices.epics.pva.shutter.EpicsShutter",
        description="Motion control pneumatic axis #415",
        readpv="TBL-TBL:MC-Pne-415:ShtAuxBits07",
        writepv="TBL-TBL:MC-Pne-415:ShtOpen",
        statuspv="TBL-TBL:MC-Pne-415:ShtStatusCode",
        msgtxt="TBL-TBL:MC-Pne-415:ShtMsgTxt",
        resetpv="TBL-TBL:MC-Pne-415:ShtErrRst",
        pva=True,
        monitor=True,
    ),
    mc_pne_416=device(
        "nicos_ess.devices.epics.pva.shutter.EpicsShutter",
        description="Motion control pneumatic axis #416",
        readpv="TBL-TBL:MC-Pne-416:ShtAuxBits07",
        writepv="TBL-TBL:MC-Pne-416:ShtOpen",
        statuspv="TBL-TBL:MC-Pne-416:ShtStatusCode",
        msgtxt="TBL-TBL:MC-Pne-416:ShtMsgTxt",
        resetpv="TBL-TBL:MC-Pne-416:ShtErrRst",
        pva=True,
        monitor=True,
    ),
    mc_mtr_401=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Motion control electrical axis #401",
        motorpv="TBL-TBL:MC-Pos-401:Mtr",
        monitor_deadband=0.01,
    ),
    mc_mtr_402=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Motion control electrical axis #402",
        motorpv="TBL-TBL:MC-Pos-402:Mtr",
        monitor_deadband=0.01,
    ),
    small_slit_1_left=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Small slit 1 left blade",
        motorpv="TBL-TBL:MC-Pos-403:Mtr",
        monitor_deadband=0.01,
    ),
    small_slit_1_right=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Small slit 1 right blade",
        motorpv="TBL-TBL:MC-Pos-404:Mtr",
        monitor_deadband=0.01,
    ),
    small_slit_1_lower=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Small slit 1 lower blade",
        motorpv="TBL-TBL:MC-Pos-405:Mtr",
        monitor_deadband=0.01,
    ),
    small_slit_1_upper=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Small slit 1 upper blade",
        motorpv="TBL-TBL:MC-Pos-406:Mtr",
        monitor_deadband=0.01,
    ),
    large_slit_right=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Large slit right blade",
        motorpv="TBL-TBL:MC-Pos-407:Mtr",
        monitor_deadband=0.01,
    ),
    large_slit_left=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Large slit left blade",
        motorpv="TBL-TBL:MC-Pos-408:Mtr",
        monitor_deadband=0.01,
    ),
    large_slit_upper=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Large slit upper blade",
        motorpv="TBL-TBL:MC-Pos-409:Mtr",
        monitor_deadband=0.01,
    ),
    large_slit_lower=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Large slit lower blade",
        motorpv="TBL-TBL:MC-Pos-410:Mtr",
        monitor_deadband=0.01,
    ),
    small_slit_2_right=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Small slit 2 right blade",
        motorpv="TBL-TBL:MC-Pos-411:Mtr",
        monitor_deadband=0.01,
    ),
    small_slit_2_left=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Small slit 2 left blade",
        motorpv="TBL-TBL:MC-Pos-412:Mtr",
        monitor_deadband=0.01,
    ),
    small_slit_2_upper=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Small slit 2 upper blade",
        motorpv="TBL-TBL:MC-Pos-413:Mtr",
        monitor_deadband=0.01,
    ),
    small_slit_2_lower=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Small slit 2 lower blade",
        motorpv="TBL-TBL:MC-Pos-414:Mtr",
        monitor_deadband=0.01,
    ),
)
