description = "Beamstop system for LoKI"

pv_root = "LOKI-DtBS1:"

devices = dict(
    motor_x_stage=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Detector beamstop X - electrical axis 3 in motion cabinet 5",
        motorpv=f"{pv_root}MC-LinX-01:Mtr",
        monitor_deadband=0.01,
        speed=5,
    ),
    x_stage=device(
        "nicos_ess.devices.mapped_controller.MappedController",
        controlled_device="motor_x_stage",
        mapping={"Max retracted": 1},
    ),
    motor_y_stage=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Detector beamstop Y - electrical axis 4 in motion cabinet 5",
        motorpv=f"{pv_root}MC-LinY-01:Mtr",
        monitor_deadband=0.01,
        speed=4,
        offset=32.5,
    ),
    y_stage=device(
        "nicos_ess.devices.mapped_controller.MappedController",
        controlled_device="motor_y_stage",
        mapping={"In beam": 0},
    ),
    motor_beam_stop_z1=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Detector beamstop Z1 M4 Transmission - electrical axis 5 in motion cabinet 5",
        motorpv=f"{pv_root}MC-LinZ-01:Mtr",
        monitor_deadband=0.01,
        speed=15,
        offset=54.63,
    ),
    beam_monitor_m4=device(
        "nicos_ess.devices.mapped_controller.MappedController",
        controlled_device="motor_beam_stop_z1",
        mapping={"Parked": 932.87, "In beam": 0},
    ),
    motor_beam_stop_z2=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Detector beamstop Z2 20x25 - electrical axis 6 in motion cabinet 5",
        motorpv=f"{pv_root}MC-LinZ-02:Mtr",
        monitor_deadband=0.01,
        speed=10,
        offset=59.32,
    ),
    beam_stop_z2=device(
        "nicos_ess.devices.mapped_controller.MappedController",
        controlled_device="motor_beam_stop_z2",
        mapping={"Parked": 918.678, "In beam": 0},
        visibility=(),
    ),
    motor_beam_stop_z3=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Detector beamstop Z3 50x60 - electrical axis 7 in motion cabinet 5",
        motorpv=f"{pv_root}MC-LinZ-03:Mtr",
        monitor_deadband=0.01,
        speed=10,
        offset=55.6,
    ),
    beam_stop_z3=device(
        "nicos_ess.devices.mapped_controller.MappedController",
        controlled_device="motor_beam_stop_z3",
        mapping={"Parked": 931.9, "In beam": 0},
        visibility=(),
    ),
    motor_beam_stop_z4=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Detector beamstop Z4 65x75 - electrical axis 8 in motion cabinet 5",
        motorpv=f"{pv_root}MC-LinZ-04:Mtr",
        monitor_deadband=0.01,
        speed=10,
        offset=57.3,
    ),
    beam_stop_z4=device(
        "nicos_ess.devices.mapped_controller.MappedController",
        controlled_device="motor_beam_stop_z4",
        mapping={"Parked": 929.7, "In beam": 0},
        visibility=(),
    ),
    motor_beam_stop_z5=device(
        "nicos_ess.devices.epics.pva.motor.EpicsMotor",
        description="Detector beamstop Z5 100x105 - electrical axis 9 in motion cabinet 5",
        motorpv=f"{pv_root}MC-LinZ-05:Mtr",
        monitor_deadband=0.01,
        speed=10,
        offset=54.6,
    ),
    beam_stop_z5=device(
        "nicos_ess.devices.mapped_controller.MappedController",
        controlled_device="motor_beam_stop_z5",
        mapping={"Parked": 935.29, "In beam": 0},
        visibility=(),
    ),
    beam_stop_selector=device(
        "nicos_ess.devices.mapped_controller.MultiTargetMapping",
        controlled_devices=[
            "x_stage",
            "y_stage",
            "beam_monitor_m4",
            "beam_stop_z2",
            "beam_stop_z3",
            "beam_stop_z4",
            "beam_stop_z5",
        ],
        mapping={
            "No beamstop": (
                "Max retracted",
                "In beam",
                "Parked",
                "Parked",
                "Parked",
                "Parked",
                "Parked",
            ),
            "Beamstop Z1": (
                "Max retracted",
                "In beam",
                "In beam",
                "Parked",
                "Parked",
                "Parked",
                "Parked",
            ),
            "Beamstop Z2": (
                "Max retracted",
                "In beam",
                "Parked",
                "In beam",
                "Parked",
                "Parked",
                "Parked",
            ),
            "Beamstop Z1+Z2": (
                "Max retracted",
                "In beam",
                "In beam",
                "In beam",
                "Parked",
                "Parked",
                "Parked",
            ),
            "Beamstop Z3": (
                "Max retracted",
                "In beam",
                "Parked",
                "Parked",
                "In beam",
                "Parked",
                "Parked",
            ),
            "Beamstop Z1+Z3": (
                "Max retracted",
                "In beam",
                "In beam",
                "Parked",
                "In beam",
                "Parked",
                "Parked",
            ),
            "Beamstop Z4": (
                "Max retracted",
                "In beam",
                "Parked",
                "Parked",
                "Parked",
                "In beam",
                "Parked",
            ),
            "Beamstop Z1+Z4": (
                "Max retracted",
                "In beam",
                "In beam",
                "Parked",
                "Parked",
                "In beam",
                "Parked",
            ),
            "Beamstop Z5": (
                "Max retracted",
                "In beam",
                "Parked",
                "Parked",
                "Parked",
                "Parked",
                "In beam",
            ),
            "Beamstop Z1+Z5": (
                "Max retracted",
                "In beam",
                "In beam",
                "Parked",
                "Parked",
                "Parked",
                "In beam",
            ),
        },
        default_target="No beamstop",
    ),
)
