description = "The choppers in chopper system 3 for LOKI"

pv_root_1 = "LOKI-ChpSy3:Chop-SFOC-101:"
pv_root_2 = "LOKI-ChpSy3:Chop-SFOC-102:"
chic_root = "LOKI-ChpSy3:Chop-CHIC-001:"

devices = dict(
    foc1_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{pv_root_1}ChopState_R",
        visibility=(),
    ),
    foc1_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv=f"{pv_root_1}C_ExecuteUser",
        writepv=f"{pv_root_1}C_ExecuteUser",
        requires={"level": "admin"},
        visibility=(),
    ),
    foc1_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{pv_root_1}Spd_R",
        writepv=f"{pv_root_1}Spd_S",
        precision=0.1,
        mapping={"14": 14, "7": 7, "0": 0, "-7": -7, "-14": -14},
    ),
    foc1_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{pv_root_1}ChopDly-S",
        writepv=f"{pv_root_1}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    foc1_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc1_delay",
        mapped_speed_dev="foc1_speed",
        offset=0,
        unit="degrees",
    ),
    foc1_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{pv_root_1}DiffTSSamples",
        unit="ns",
        visibility=(
            "metadata",
            "namespace",
        ),
    ),
    foc1_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{pv_root_1}InPhaseTS-R",
    ),
    foc1_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{pv_root_1}Pos_R",
        writepv=f"{pv_root_1}Park_S",
        visibility=(),
        mapping={
            "park pos 0": 0,
            "park pos 1": 45,
            "park pos 2": 90,
            "park pos 3": 180,
        },
    ),
    foc1_park_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The park status for the SFOC1 chopper.",
        readpv=f"{pv_root_1}ParkStatus_R",
    ),
    foc1_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the SFOC1 chopper.",
        readpv=f"{pv_root_1}C_Park",
        writepv=f"{pv_root_1}C_Park",
    ),
    foc1_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv=f"{chic_root}ConnectedR",
        visibility=(),
        pva=True,
    ),
    foc1_alarms=device(
        "nicos_ess.devices.epics.chopper.NewChopperAlarms",
        description="The chopper alarms",
        pv_root=pv_root_1,
        visibility=(),
    ),
    foc1=device(
        "nicos_ess.devices.epics.chopper.NewEssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="foc1_status",
        command="foc1_control",
        speed="foc1_speed",
        chic_conn="foc1_chic",
        alarms="foc1_alarms",
        slit_edges=[[0, 190]],
        resolver_offset=-145,
    ),
    foc2_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{pv_root_2}ChopState_R",
        visibility=(),
    ),
    foc2_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv=f"{pv_root_2}C_ExecuteUser",
        writepv=f"{pv_root_2}C_ExecuteUser",
        requires={"level": "admin"},
        visibility=(),
    ),
    foc2_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{pv_root_2}Spd_R",
        writepv=f"{pv_root_2}Spd_S",
        precision=0.1,
        mapping={"14": 14, "7": 7, "0": 0, "-7": -7, "-14": -14},
    ),
    foc2_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{pv_root_2}ChopDly-S",
        writepv=f"{pv_root_2}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    foc2_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc2_delay",
        mapped_speed_dev="foc2_speed",
        offset=0,
        unit="degrees",
    ),
    foc2_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{pv_root_2}DiffTSSamples",
        unit="ns",
        visibility=(
            "metadata",
            "namespace",
        ),
    ),
    foc2_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{pv_root_2}InPhaseTS-R",
    ),
    foc2_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{pv_root_2}Pos_R",
        writepv=f"{pv_root_2}Park_S",
        visibility=(),
        mapping={
            "park pos 0": 0,
            "park pos 1": 45,
            "park pos 2": 90,
            "park pos 3": 180,
        },
    ),
    foc2_park_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The park status for the SFOC2 chopper.",
        readpv=f"{pv_root_2}ParkStatus_R",
    ),
    foc2_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the SFOC2 chopper.",
        readpv=f"{pv_root_2}C_Park",
        writepv=f"{pv_root_2}C_Park",
    ),
    foc2_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv=f"{chic_root}ConnectedR",
        visibility=(),
    ),
    foc2_alarms=device(
        "nicos_ess.devices.epics.chopper.NewChopperAlarms",
        description="The chopper alarms",
        pv_root=pv_root_2,
        visibility=(),
    ),
    foc2=device(
        "nicos_ess.devices.epics.chopper.NewEssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="foc2_status",
        command="foc2_control",
        speed="foc2_speed",
        chic_conn="foc2_chic",
        alarms="foc2_alarms",
        slit_edges=[[0, 190]],
        resolver_offset=35,
    ),
)
