description = "The choppers in chopper system 3 for LOKI"

pv_root_1 = "LOKI-ChpSy3:Chop-SFOC-101:"
pv_root_2 = "LOKI-ChpSy3:Chop-SFOC-102:"
chic_root = "LOKI-ChpSy3:Chop-CHIC-001:"

devices = dict(
    foc1_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv="{}ChopState_R".format(pv_root_1),
        visibility=(),
    ),
    foc1_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv="{}C_Execute".format(pv_root_1),
        writepv="{}C_Execute".format(pv_root_1),
        requires={"level": "admin"},
        visibility=(),
    ),
    foc1_speed=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current speed.",
        readpv="{}Spd_R".format(pv_root_1),
        writepv="{}Spd_S".format(pv_root_1),
        abslimits=(0.0, 0.0),
        precision=0.1,
    ),
    foc1_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv="{}ChopDly-S".format(pv_root_1),
        writepv="{}ChopDly-S".format(pv_root_1),
        abslimits=(0.0, 0.0),
    ),
    foc1_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc1_delay",
        speed_dev="foc1_speed",
        offset=0,
        unit="degrees",
    ),
    foc1_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv="{}DiffTSSamples".format(pv_root_1),
        unit="ns",
        visibility=(
            "metadata",
            "namespace",
        ),
    ),
    foc1_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv="{}InPhs_R".format(pv_root_1),
    ),
    foc1_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The chopper's park angle.",
        readpv="{}Pos_R".format(pv_root_1),
        writepv="{}Park_S".format(pv_root_1),
        visibility=(),
    ),
    foc1_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the SFOC1 chopper.",
        readpv="{}ParkPos_S".format(pv_root_1),
        writepv="{}ParkPos_S".format(pv_root_1),
    ),
    foc1_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv="{}ConnectedR".format(chic_root),
        visibility=(),
        pva=True,
    ),
    foc1_alarms=device(
        "nicos_ess.devices.epics.chopper.ChopperAlarms",
        description="The chopper alarms",
        pv_root=pv_root_1,
        visibility=(),
    ),
    foc1=device(
        "nicos_ess.devices.epics.chopper.EssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="foc1_status",
        command="foc1_control",
        speed="foc1_speed",
        chic_conn="foc1_chic",
        alarms="foc1_alarms",
        slit_edges=[[0, 190]],
        resolver_offset=-145,
    ),
    foc2_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv="{}ChopState_R".format(pv_root_2),
        visibility=(),
    ),
    foc2_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv="{}C_Execute".format(pv_root_2),
        writepv="{}C_Execute".format(pv_root_2),
        requires={"level": "admin"},
        visibility=(),
    ),
    foc2_speed=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current speed.",
        readpv="{}Spd_R".format(pv_root_2),
        writepv="{}Spd_S".format(pv_root_2),
        abslimits=(0.0, 0.0),
        precision=0.1,
    ),
    foc2_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv="{}ChopDly-S".format(pv_root_2),
        writepv="{}ChopDly-S".format(pv_root_2),
        abslimits=(0.0, 0.0),
    ),
    foc2_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc2_delay",
        speed_dev="foc2_speed",
        offset=0,
        unit="degrees",
    ),
    foc2_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv="{}DiffTSSamples".format(pv_root_2),
        unit="ns",
        visibility=(
            "metadata",
            "namespace",
        ),
    ),
    foc2_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv="{}InPhs_R".format(pv_root_2),
    ),
    foc2_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The chopper's park angle.",
        readpv="{}Pos_R".format(pv_root_2),
        writepv="{}Park_S".format(pv_root_2),
        visibility=(),
    ),
    foc2_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the SFOC2 chopper.",
        readpv="{}ParkPos_S".format(pv_root_2),
        writepv="{}ParkPos_S".format(pv_root_2),
    ),
    foc2_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv="{}ConnectedR".format(chic_root),
        visibility=(),
    ),
    foc2_alarms=device(
        "nicos_ess.devices.epics.chopper.ChopperAlarms",
        description="The chopper alarms",
        pv_root=pv_root_2,
        visibility=(),
    ),
    foc2=device(
        "nicos_ess.devices.epics.chopper.EssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="foc2_status",
        command="foc2_control",
        speed="foc2_speed",
        chic_conn="foc2_chic",
        alarms="foc2_alarms",
        slit_edges=[[0, 190]],
        resolver_offset=35,
    ),
)
