description = "The just-bin-it histogrammer."

devices = dict(
    det_image1=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="ymir_visualisation",
        data_topic="bifrost_detector",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D DET",
        det_width=900,
        det_height=15,
        det_range=(1, 13500),
    ),
    det_image2=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        hist_topic="ymir_visualisation",
        data_topic="bifrost_detector",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D TOF",
        det_width=900,
        det_height=15,
        det_range=(1, 13500),
        tof_range=(0, 10000000),
    ),
    bifrost_bm1_image=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="bifrost_beam_monitor",
        source="cbm1",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        hist_topic="ymir_visualisation",
    ),
    bifrost_bm4_image=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="bifrost_beam_monitor",
        source="cbm4",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="2-D TOF",
        det_width=32,
        det_height=32,
        det_range=(1, 1024),
        hist_topic="ymir_visualisation",
    ),
    bifrost_bm5_image=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="bifrost_beam_monitor",
        source="cbm5",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        hist_topic="ymir_visualisation",
    ),
    loki_bm0_image=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="loki_beam_monitor",
        source="cbm0",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        hist_topic="ymir_visualisation",
    ),
    loki_bm1_image=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="loki_beam_monitor",
        source="cbm1",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        hist_topic="ymir_visualisation",
    ),
    loki_bm2_image=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="loki_beam_monitor",
        source="cbm2",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        hist_topic="ymir_visualisation",
    ),
    loki_bm3_image=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="loki_beam_monitor",
        source="cbm3",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        hist_topic="ymir_visualisation",
    ),
    loki_bm4_image=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="A just-bin-it image channel",
        data_topic="loki_beam_monitor",
        source="cbm4",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="evts",
        hist_type="1-D TOF",
        hist_topic="ymir_visualisation",
    ),
    timer=device(
        "nicos_ess.devices.timer.TimerChannel",
        description="Timer",
        fmtstr="%.2f",
        unit="s",
    ),
    # pulse_counter=device(
    #     "nicos_ess.devices.epics.pulse_counter.PulseCounter",
    #     description="EVR Pulse Counter",
    #     readpv="YMIR-TS:Ctrl-EVR-01:EvtACnt-I",
    #     fmtstr="%d",
    # ),
    det=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItDetector",
        description="The just-bin-it histogrammer",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="",
        command_topic="ymir_jbi_commands",
        response_topic="ymir_jbi_responses",
        statustopic=["ymir_jbi_heartbeat"],
        images=[
            "det_image1",
            "det_image2",
            "bifrost_bm1_image",
            "bifrost_bm4_image",
            "bifrost_bm5_image",
            "loki_bm0_image",
            "loki_bm1_image",
            "loki_bm2_image",
            "loki_bm3_image",
            "loki_bm4_image",
        ],
        timers=["timer"],
        # counters=["pulse_counter"],
        hist_schema="hs01",
        event_schema="ev44",
    ),
)

startupcode = """
SetDetectors(det)
"""
