description = "The choppers in chopper system 2 for ODIN"

bpc2_pv_root = "ODIN-ChpSy2:Chop-BPC-202:"
foc2_pv_root = "ODIN-ChpSy2:Chop-FOC-201:"
foc3_pv_root = "ODIN-ChpSy2:Chop-FOC-301:"
foc4_pv_root = "ODIN-ChpSy2:Chop-FOC-401:"
chic_root = "ODIN-ChpSy2:Chop-CHIC-001:"
vacuum_pv_root = "ODIN-VacBnkr:Vac-VGP-"

# The Airbus controller owns the physical TDC parameterization.  The canonical
# GUI model uses 0.0 as the controller-relative Airbus phase zero.

devices = dict(
    bpc2_chopper_log=device(
        "nicos_ess.devices.epics.pva.EpicsStringReadable",
        description="The logs from chopper controller",
        readpv="{}Log_R".format(bpc2_pv_root),
        visibility=(),
    ),
    bpc2_chopper_levitation_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper levitation status.",
        readpv="{}LeviStatus_R".format(bpc2_pv_root),
        visibility=(),
    ),
    bpc2_chopper_motor_temperature=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The temperature of the motor of the chopper",
        readpv="{}MtrTemp_R".format(bpc2_pv_root),
        visibility=(),
    ),
    bpc2_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv="{}ChopState_R".format(bpc2_pv_root),
        visibility=(),
    ),
    bpc2_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv="{}Spd_R".format(bpc2_pv_root),
        writepv="{}Spd_S".format(bpc2_pv_root),
        precision=0.1,
        mapping={"14 Hz": 14, "7 Hz": 7, "0 Hz": 0},
    ),
    bpc2_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv="{}ChopDly-S".format(bpc2_pv_root),
        writepv="{}ChopDly-S".format(bpc2_pv_root),
        abslimits=(0.0, 0.0),
    ),
    bpc2_chopper_total_delay=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description=(
            "The total delay (MechDly-S + BeamPosDly-S + ChopDly-S). "
            "The full delay that is applied on proton on target event for "
            "the driving signal of the chopper."
        ),
        readpv="{}TotDly".format(bpc2_pv_root),
        visibility=("metadata", "namespace"),
    ),
    bpc2_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="bpc2_chopper_delay",
        mapped_speed_dev="bpc2_chopper_speed",
        offset=0.0,
        unit="degrees",
    ),
    bpc2_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv="{}DiffTSSamples".format(bpc2_pv_root),
        unit="ns",
        visibility=("metadata", "namespace"),
    ),
    bpc2_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv="{}InPhs_R".format(bpc2_pv_root),
    ),
    bpc2_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The chopper's park angle.",
        readpv="{}Pos_R".format(bpc2_pv_root),
        writepv="{}ParkAngle_S".format(bpc2_pv_root),
        visibility=(),
        mapping={"park opening 0": -141.795},
    ),
    bpc2_chopper_park_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The park status for the BPC2 chopper.",
        readpv="{}ParkStatus_R".format(bpc2_pv_root),
    ),
    bpc2_chopper_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the BPC2 chopper.",
        readpv="{}C_Park".format(bpc2_pv_root),
        writepv="{}C_Park".format(bpc2_pv_root),
    ),
    bpc2_chopper_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv="{}ConnectedR".format(chic_root),
        visibility=(),
        pva=True,
    ),
    bpc2_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.ChopperAlarmsV2",
        description="The chopper alarms",
        pv_root=bpc2_pv_root,
        visibility=(),
    ),
    bpc2_chopper=device(
        "nicos_ess.devices.epics.chopper.OdinChopperController",
        description="The chopper controller",
        pv_root=bpc2_pv_root,
        pollinterval=0.5,
        maxage=None,
        monitor=True,
        slit_edges=[[0.0, 67.49]],
        mapping={
            "Start": "start",
            "AStart": "a_start",
            "Stop": "stop",
            "Park": "park",
        },
        speed="bpc2_chopper_speed",
        total_delay="bpc2_chopper_total_delay",
        park_angle="bpc2_chopper_park_angle",
        delay_errors="bpc2_chopper_delay_errors",
        chic_conn="bpc2_chopper_chic",
        alarms="bpc2_chopper_alarms",
        motor_position="upstream",
        positive_speed_rotation_direction="CW",
        resolver_positive_direction="CCW",
        parked_opening_index=0,
        tdc_resolver_position=0.0,
        park_open_angle=-141.795,
        disk_delay=0.0,
    ),
    bpc2_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv="{}103:PrsR".format(vacuum_pv_root),
        fmtstr="%.2e",
    ),
    foc2_chopper_log=device(
        "nicos_ess.devices.epics.pva.EpicsStringReadable",
        description="The logs from chopper controller",
        readpv="{}Log_R".format(foc2_pv_root),
        visibility=(),
    ),
    foc2_chopper_levitation_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper levitation status.",
        readpv="{}LeviStatus_R".format(foc2_pv_root),
        visibility=(),
    ),
    foc2_chopper_motor_temperature=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The temperature of the motor of the chopper",
        readpv="{}MtrTemp_R".format(foc2_pv_root),
        visibility=(),
    ),
    foc2_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv="{}ChopState_R".format(foc2_pv_root),
        visibility=(),
    ),
    foc2_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv="{}Spd_R".format(foc2_pv_root),
        writepv="{}Spd_S".format(foc2_pv_root),
        precision=0.1,
        mapping={"14 Hz": 14, "7 Hz": 7, "0 Hz": 0, "21 Hz": 21, "42 Hz": 42},
    ),
    foc2_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv="{}ChopDly-S".format(foc2_pv_root),
        writepv="{}ChopDly-S".format(foc2_pv_root),
        abslimits=(0.0, 0.0),
    ),
    foc2_chopper_total_delay=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description=(
            "The total delay (MechDly-S + BeamPosDly-S + ChopDly-S). "
            "The full delay that is applied on proton on target event for "
            "the driving signal of the chopper."
        ),
        readpv="{}TotDly".format(foc2_pv_root),
        visibility=("metadata", "namespace"),
    ),
    foc2_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc2_chopper_delay",
        mapped_speed_dev="foc2_chopper_speed",
        offset=0.0,
        unit="degrees",
    ),
    foc2_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv="{}DiffTSSamples".format(foc2_pv_root),
        unit="ns",
        visibility=("metadata", "namespace"),
    ),
    foc2_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv="{}InPhs_R".format(foc2_pv_root),
    ),
    foc2_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The chopper's park angle.",
        readpv="{}Pos_R".format(foc2_pv_root),
        writepv="{}ParkAngle_S".format(foc2_pv_root),
        visibility=(),
        mapping={
            "park opening 0": 67.15,
            "park opening 1": 127.07,
            "park opening 2": -165.08,
            "park opening 3": -101.46,
            "park opening 4": -41.97,
            "park opening 5": 13.98,
        },
    ),
    foc2_chopper_park_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The park status for the FOC2 chopper.",
        readpv="{}ParkStatus_R".format(foc2_pv_root),
    ),
    foc2_chopper_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the FOC2 chopper.",
        readpv="{}C_Park".format(foc2_pv_root),
        writepv="{}C_Park".format(foc2_pv_root),
    ),
    foc2_chopper_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv="{}ConnectedR".format(chic_root),
        visibility=(),
        pva=True,
    ),
    foc2_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.ChopperAlarmsV2",
        description="The chopper alarms",
        pv_root=foc2_pv_root,
        visibility=(),
    ),
    foc2_chopper=device(
        "nicos_ess.devices.epics.chopper.OdinChopperController",
        description="The chopper controller",
        pv_root=foc2_pv_root,
        pollinterval=0.5,
        maxage=None,
        monitor=True,
        slit_edges=[
            [0.0, 34.31],
            [60.625, 93.525],
            [128.155, 161.695],
            [191.47, 225.62],
            [250.85, 285.22],
            [306.54, 341.43],
        ],
        mapping={"Start": "start", "AStart": "a_start", "Stop": "stop", "Park": "park"},
        speed="foc2_chopper_speed",
        total_delay="foc2_chopper_total_delay",
        park_angle="foc2_chopper_park_angle",
        delay_errors="foc2_chopper_delay_errors",
        chic_conn="foc2_chopper_chic",
        alarms="foc2_chopper_alarms",
        motor_position="downstream",
        positive_speed_rotation_direction="CCW",
        resolver_positive_direction="CCW",
        parked_opening_index=0,
        tdc_resolver_position=0.0,
        park_open_angle=67.15,
        disk_delay=0.0,
    ),
    foc2_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv="{}103:PrsR".format(vacuum_pv_root),
        fmtstr="%.2e",
    ),
    foc3_chopper_log=device(
        "nicos_ess.devices.epics.pva.EpicsStringReadable",
        description="The logs from chopper controller",
        readpv="{}Log_R".format(foc3_pv_root),
        visibility=(),
    ),
    foc3_chopper_levitation_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper levitation status.",
        readpv="{}LeviStatus_R".format(foc3_pv_root),
        visibility=(),
    ),
    foc3_chopper_motor_temperature=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The temperature of the motor of the chopper",
        readpv="{}MtrTemp_R".format(foc3_pv_root),
        visibility=(),
    ),
    foc3_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv="{}ChopState_R".format(foc3_pv_root),
        visibility=(),
    ),
    foc3_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv="{}Spd_R".format(foc3_pv_root),
        writepv="{}Spd_S".format(foc3_pv_root),
        precision=0.1,
        mapping={"14 Hz": 14, "7 Hz": 7, "0 Hz": 0, "28 Hz": 28},
    ),
    foc3_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv="{}ChopDly-S".format(foc3_pv_root),
        writepv="{}ChopDly-S".format(foc3_pv_root),
        abslimits=(0.0, 0.0),
    ),
    foc3_chopper_total_delay=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description=(
            "The total delay (MechDly-S + BeamPosDly-S + ChopDly-S). "
            "The full delay that is applied on proton on target event for "
            "the driving signal of the chopper."
        ),
        readpv="{}TotDly".format(foc3_pv_root),
        visibility=("metadata", "namespace"),
    ),
    foc3_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc3_chopper_delay",
        mapped_speed_dev="foc3_chopper_speed",
        offset=0.0,
        unit="degrees",
    ),
    foc3_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv="{}DiffTSSamples".format(foc3_pv_root),
        unit="ns",
        visibility=("metadata", "namespace"),
    ),
    foc3_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv="{}InPhs_R".format(foc3_pv_root),
    ),
    foc3_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The chopper's park angle.",
        readpv="{}Pos_R".format(foc3_pv_root),
        writepv="{}ParkAngle_S".format(foc3_pv_root),
        visibility=(),
        mapping={
            "park opening 0": -53.92,
            "park opening 1": -135.0,
            "park opening 2": 161.95,
            "park opening 3": 102.82,
            "park opening 4": 47.38,
            "park opening 5": -4.61,
        },
    ),
    foc3_chopper_park_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The park status for the FOC3 chopper.",
        readpv="{}ParkStatus_R".format(foc3_pv_root),
    ),
    foc3_chopper_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the FOC3 chopper.",
        readpv="{}C_Park".format(foc3_pv_root),
        writepv="{}C_Park".format(foc3_pv_root),
    ),
    foc3_chopper_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv="{}ConnectedR".format(chic_root),
        visibility=(),
        pva=True,
    ),
    foc3_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.ChopperAlarmsV2",
        description="The chopper alarms",
        pv_root=foc3_pv_root,
        visibility=(),
    ),
    foc3_chopper=device(
        "nicos_ess.devices.epics.chopper.OdinChopperController",
        description="The chopper controller",
        pv_root=foc3_pv_root,
        pollinterval=0.5,
        maxage=None,
        monitor=True,
        slit_edges=[
            [0.0, 36.06],
            [78.95, 119.27],
            [142.355, 181.965],
            [201.82, 240.76],
            [257.575, 295.885],
            [309.86, 347.58],
        ],
        mapping={"Start": "start", "AStart": "a_start", "Stop": "stop", "Park": "park"},
        speed="foc3_chopper_speed",
        total_delay="foc3_chopper_total_delay",
        park_angle="foc3_chopper_park_angle",
        delay_errors="foc3_chopper_delay_errors",
        chic_conn="foc3_chopper_chic",
        alarms="foc3_chopper_alarms",
        motor_position="upstream",
        positive_speed_rotation_direction="CW",
        resolver_positive_direction="CCW",
        parked_opening_index=0,
        tdc_resolver_position=0.0,
        park_open_angle=-53.92,
        disk_delay=0.0,
    ),
    foc3_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv="{}105:PrsR".format(vacuum_pv_root),
        fmtstr="%.2e",
    ),
    foc4_chopper_log=device(
        "nicos_ess.devices.epics.pva.EpicsStringReadable",
        description="The logs from chopper controller",
        readpv="{}Log_R".format(foc4_pv_root),
        visibility=(),
    ),
    foc4_chopper_levitation_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper levitation status.",
        readpv="{}LeviStatus_R".format(foc4_pv_root),
        visibility=(),
    ),
    foc4_chopper_motor_temperature=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The temperature of the motor of the chopper",
        readpv="{}MtrTemp_R".format(foc4_pv_root),
        visibility=(),
    ),
    foc4_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv="{}ChopState_R".format(foc4_pv_root),
        visibility=(),
    ),
    foc4_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv="{}Spd_R".format(foc4_pv_root),
        writepv="{}Spd_S".format(foc4_pv_root),
        precision=0.1,
        mapping={"14 Hz": 14, "7 Hz": 7, "0 Hz": 0},
    ),
    foc4_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv="{}ChopDly-S".format(foc4_pv_root),
        writepv="{}ChopDly-S".format(foc4_pv_root),
        abslimits=(0.0, 0.0),
    ),
    foc4_chopper_total_delay=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description=(
            "The total delay (MechDly-S + BeamPosDly-S + ChopDly-S). "
            "The full delay that is applied on proton on target event for "
            "the driving signal of the chopper."
        ),
        readpv="{}TotDly".format(foc4_pv_root),
        visibility=("metadata", "namespace"),
    ),
    foc4_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc4_chopper_delay",
        mapped_speed_dev="foc4_chopper_speed",
        offset=0.0,
        unit="degrees",
    ),
    foc4_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv="{}DiffTSSamples".format(foc4_pv_root),
        unit="ns",
        visibility=("metadata", "namespace"),
    ),
    foc4_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv="{}InPhs_R".format(foc4_pv_root),
    ),
    foc4_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The chopper's park angle.",
        readpv="{}Pos_R".format(foc4_pv_root),
        writepv="{}ParkAngle_S".format(foc4_pv_root),
        visibility=(),
        mapping={
            "park opening 0": -129.47,
            "park opening 1": 186.59,
            "park opening 2": 145.38,
            "park opening 3": 106.74,
            "park opening 4": 70.51,
            "park opening 5": 35.98,
        },
    ),
    foc4_chopper_park_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The park status for the FOC4 chopper.",
        readpv="{}ParkStatus_R".format(foc4_pv_root),
    ),
    foc4_chopper_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the FOC4 chopper.",
        readpv="{}C_Park".format(foc4_pv_root),
        writepv="{}C_Park".format(foc4_pv_root),
    ),
    foc4_chopper_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv="{}ConnectedR".format(chic_root),
        visibility=(),
        pva=True,
    ),
    foc4_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.ChopperAlarmsV2",
        description="The chopper alarms",
        pv_root=foc4_pv_root,
        visibility=(),
    ),
    foc4_chopper=device(
        "nicos_ess.devices.epics.chopper.OdinChopperController",
        description="The chopper controller",
        pv_root=foc4_pv_root,
        pollinterval=0.5,
        maxage=None,
        monitor=True,
        slit_edges=[
            [0.0, 32.98],
            [44.52, 76.34],
            [86.27, 117.01],
            [125.645, 154.915],
            [162.125, 190.895],
            [197.66, 224.42],
        ],
        mapping={"Start": "start", "AStart": "a_start", "Stop": "stop", "Park": "park"},
        speed="foc4_chopper_speed",
        total_delay="foc4_chopper_total_delay",
        park_angle="foc4_chopper_park_angle",
        delay_errors="foc4_chopper_delay_errors",
        chic_conn="foc4_chopper_chic",
        alarms="foc4_chopper_alarms",
        motor_position="upstream",
        positive_speed_rotation_direction="CW",
        resolver_positive_direction="CCW",
        parked_opening_index=0,
        tdc_resolver_position=0.0,
        park_open_angle=-129.47,
        disk_delay=0.0,
    ),
    foc4_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv="{}107:PrsR".format(vacuum_pv_root),  # same as foc
        fmtstr="%.2e",
    ),
)
