description = "The choppers in chopper system 1 for ODIN"

wfmc1_pv_root = "ODIN-ChpSy1:Chop-WFMC-101:"
wfmc2_pv_root = "ODIN-ChpSy1:Chop-WFMC-102:"
foc1_pv_root = "ODIN-ChpSy1:Chop-FOC-101:"
bpc1_pv_root = "ODIN-ChpSy1:Chop-BPC-102:"
vacuum_pv_root = "ODIN-VacBnkr:Vac-VGP-"
chpsy1_chic_pv_root = "ODIN-ChpSy1:Chop-CHIC-001:"

devices = dict(
    chpsy1_chopper_chic=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The status of the CHIC connection.",
        readpv=f"{chpsy1_chic_pv_root}ConnectedR",
        visibility=(),
        pva=True,
    ),
    wfmc1_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{wfmc1_pv_root}ChopState_R",
        visibility=(),
    ),
    wfmc1_chopper_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv=f"{wfmc1_pv_root}C_ExecuteUser",
        writepv=f"{wfmc1_pv_root}C_ExecuteUser",
        requires={"level": "admin"},
        visibility=(),
    ),
    wfmc1_chopper_speed=device(
        # Should be EpicsAnalogMoveable later
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{wfmc1_pv_root}Spd_R",
        writepv=f"{wfmc1_pv_root}Spd_S",
        precision=0.1,
        mapping={"14": 14, "7": 7, "0": 0, "28": 28, "56": 56},
    ),
    wfmc1_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{wfmc1_pv_root}ChopDly-S",
        writepv=f"{wfmc1_pv_root}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    wfmc1_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="wfmc1_chopper_delay",
        mapped_speed_dev="wfmc1_chopper_speed",
        offset=0,
        unit="degrees",
    ),
    wfmc1_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{wfmc1_pv_root}DiffTSSamples",
        unit="ns",
        visibility=(
            "metadata",
            "namespace",
        ),
    ),
    wfmc1_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{wfmc1_pv_root}InPhaseTS-R",
    ),
    wfmc1_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{wfmc1_pv_root}Pos_R",
        writepv=f"{wfmc1_pv_root}Park_S",
        visibility=(),
        mapping={
            "park pos 0": 0,
            "park pos 1": 45,
            "park pos 2": 90,
            "park pos 3": 180,
        },
    ),
    wfmc1_chopper_park_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The park status for the WLS1 chopper.",
        readpv=f"{wfmc1_pv_root}ParkStatus_R",
    ),
    wfmc1_chopper_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the WLS1 chopper.",
        readpv=f"{wfmc1_pv_root}C_Park",
        writepv=f"{wfmc1_pv_root}C_Park",
    ),
    wfmc1_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.NewChopperAlarms",
        description="The chopper alarms",
        pv_root=wfmc1_pv_root,
        visibility=(),
    ),
    wfmc1_chopper=device(
        "nicos_ess.devices.epics.chopper.NewEssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="wfmc1_chopper_status",
        command="wfmc1_chopper_control",
        speed="wfmc1_chopper_speed",
        chic_conn="chpsy1_chopper_chic",
        alarms="wfmc1_chopper_alarms",
        slit_edges=[
            [0.0, 5.7],
            [48.65, 57.65],
            [94.32, 106.32],
            [137.1, 152.0],
            [177.27, 194.77],
            [214.91, 234.91],
        ],
        resolver_offset=-8.47,
        tdc_offset=-8.47,
        spin_direction="CCW",
    ),
    wfmc1_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv=f"{vacuum_pv_root}100:PrsR",
        fmtstr="%.2e",
    ),
    wfmc2_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{wfmc2_pv_root}ChopState_R",
        visibility=(),
    ),
    wfmc2_chopper_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv=f"{wfmc2_pv_root}C_ExecuteUser",
        writepv=f"{wfmc2_pv_root}C_ExecuteUser",
        requires={"level": "admin"},
        visibility=(),
    ),
    wfmc2_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{wfmc2_pv_root}Spd_R",
        writepv=f"{wfmc2_pv_root}Spd_S",
        precision=0.1,
        mapping={"14": 14, "7": 7, "0": 0, "28": 28, "56": 56},
    ),
    wfmc2_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{wfmc2_pv_root}ChopDly-S",
        writepv=f"{wfmc2_pv_root}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    wfmc2_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="wfmc2_chopper_delay",
        mapped_speed_dev="wfmc2_chopper_speed",
        offset=0,
        unit="degrees",
    ),
    wfmc2_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{wfmc2_pv_root}DiffTSSamples",
        unit="ns",
        visibility=("metadata", "namespace"),
    ),
    wfmc2_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{wfmc2_pv_root}InPhaseTS-R",
    ),
    wfmc2_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{wfmc2_pv_root}Pos_R",
        writepv=f"{wfmc2_pv_root}Park_S",
        visibility=(),
        mapping={
            "park pos 0": 0,
            "park pos 1": 45,
            "park pos 2": 90,
            "park pos 3": 180,
        },
    ),
    wfmc2_chopper_park_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The park status for the WFMC2 chopper.",
        readpv=f"{wfmc2_pv_root}ParkStatus_R",
    ),
    wfmc2_chopper_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the WFMC2 chopper.",
        readpv=f"{wfmc2_pv_root}C_Park",
        writepv=f"{wfmc2_pv_root}C_Park",
    ),
    wfmc2_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.NewChopperAlarms",
        description="The chopper alarms",
        pv_root=wfmc1_pv_root,
        visibility=(),
    ),
    wfmc2_chopper=device(
        "nicos_ess.devices.epics.chopper.NewEssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="wfmc2_chopper_status",
        command="wfmc2_chopper_control",
        speed="wfmc2_chopper_speed",
        chic_conn="chpsy1_chopper_chic",
        alarms="wfmc2_chopper_alarms",
        slit_edges=[
            [0.0, 5.7],
            [51.89, 60.89],
            [100.59, 112.59],
            [146.21, 161.11],
            [189.05, 206.55],
            [229.19, 249.19],
        ],
        resolver_offset=-79.30,
        tdc_offset=-79.30,
        spin_direction="CW",
    ),
    wfmc2_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv=f"{vacuum_pv_root}101:PrsR",
        fmtstr="%.2e",
    ),
    foc1_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{foc1_pv_root}ChopState_R",
        visibility=(),
    ),
    foc1_chopper_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv=f"{foc1_pv_root}C_ExecuteUser",
        writepv=f"{foc1_pv_root}C_ExecuteUser",
        requires={"level": "admin"},
        visibility=(),
    ),
    foc1_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{foc1_pv_root}Spd_R",
        writepv=f"{foc1_pv_root}Spd_S",
        precision=0.1,
        mapping={"14": 14, "7": 7, "0": 0, "21": 21, "42": 42},
    ),
    foc1_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{foc1_pv_root}ChopDly-S",
        writepv=f"{foc1_pv_root}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    foc1_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc1_chopper_delay",
        mapped_speed_dev="foc1_chopper_speed",
        offset=0,
        unit="degrees",
    ),
    foc1_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{foc1_pv_root}DiffTSSamples",
        unit="ns",
        visibility=("metadata", "namespace"),
    ),
    foc1_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{foc1_pv_root}InPhaseTS-R",
    ),
    foc1_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{foc1_pv_root}Pos_R",
        writepv=f"{foc1_pv_root}Park_S",
        visibility=(),
        mapping={
            "park pos 0": 0,
            "park pos 1": 45,
            "park pos 2": 90,
            "park pos 3": 180,
        },
    ),
    foc1_chopper_park_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The park status for the WLS1 chopper.",
        readpv=f"{foc1_pv_root}ParkStatus_R",
    ),
    foc1_chopper_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the WLS1 chopper.",
        readpv=f"{foc1_pv_root}C_Park",
        writepv=f"{foc1_pv_root}C_Park",
    ),
    foc1_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.NewChopperAlarms",
        description="The chopper alarms",
        pv_root=foc1_pv_root,
        visibility=(),
    ),
    foc1_chopper=device(
        "nicos_ess.devices.epics.chopper.NewEssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="foc1_chopper_status",
        command="foc1_chopper_control",
        speed="foc1_chopper_speed",
        chic_conn="chpsy1_chopper_chic",
        alarms="foc1_chopper_alarms",
        slit_edges=[
            [0.0, 11.06],
            [45.7, 58.76],
            [88.54, 103.48],
            [128.715, 145.425],
            [166.39, 184.75],
            [204.9, 221.62],
        ],
        resolver_offset=141.215,
        tdc_offset=141.215,
        spin_direction="CCW",
    ),
    foc1_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv=f"{vacuum_pv_root}102:PrsR",
        fmtstr="%.2e",
    ),
    bpc1_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{bpc1_pv_root}ChopState_R",
        visibility=(),
    ),
    bpc1_chopper_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="Used to start and stop the chopper.",
        readpv=f"{bpc1_pv_root}C_ExecuteUser",
        writepv=f"{bpc1_pv_root}C_ExecuteUser",
        requires={"level": "admin"},
        visibility=(),
    ),
    bpc1_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{bpc1_pv_root}Spd_R",
        writepv=f"{bpc1_pv_root}Spd_S",
        precision=0.1,
        mapping={"14": 14, "7": 7, "0": 0},
    ),
    bpc1_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{bpc1_pv_root}ChopDly-S",
        writepv=f"{bpc1_pv_root}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    bpc1_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="bpc1_chopper_delay",
        mapped_speed_dev="bpc1_chopper_speed",
        offset=0,
        unit="degrees",
    ),
    bpc1_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{bpc1_pv_root}DiffTSSamples",
        unit="ns",
        visibility=("metadata", "namespace"),
    ),
    bpc1_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{bpc1_pv_root}InPhaseTS-R",
    ),
    bpc1_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{bpc1_pv_root}Pos_R",
        writepv=f"{bpc1_pv_root}Park_S",
        visibility=(),
        mapping={
            "park pos 0": 0,
            "park pos 1": 45,
            "park pos 2": 90,
            "park pos 3": 180,
        },
    ),
    bpc1_chopper_park_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The park status for the WLS1 chopper.",
        readpv=f"{bpc1_pv_root}ParkStatus_R",
    ),
    bpc1_chopper_park_control=device(
        "nicos_ess.devices.epics.pva.EpicsMappedMoveable",
        description="The park control for the WLS1 chopper.",
        readpv=f"{bpc1_pv_root}C_Park",
        writepv=f"{bpc1_pv_root}C_Park",
    ),
    bpc1_chopper_alarms=device(
        "nicos_ess.devices.epics.chopper.NewChopperAlarms",
        description="The chopper alarms",
        pv_root=bpc1_pv_root,
        visibility=(),
    ),
    bpc1_chopper=device(
        "nicos_ess.devices.epics.chopper.NewEssChopperController",
        description="The chopper controller",
        pollinterval=0.5,
        maxage=None,
        state="bpc1_chopper_status",
        command="bpc1_chopper_control",
        speed="bpc1_chopper_speed",
        chic_conn="chpsy1_chopper_chic",
        alarms="bpc1_chopper_alarms",
        slit_edges=[[0.0, 46.71]],
        resolver_offset=-161.15,
        tdc_offset=-161.15,
        spin_direction="CW",
    ),
    bpc1_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv=f"{vacuum_pv_root}102:PrsR",  # same as foc
        fmtstr="%.2e",
    ),
)
