description = "The choppers in chopper system 2 for ODIN"

bpc2_pv_root = "ODIN-ChpSy2:Chop-BPC-202:"
foc2_pv_root = "ODIN-ChpSy2:Chop-FOC-201:"
foc3_pv_root = "ODIN-ChpSy2:Chop-FOC-301:"
foc4_pv_root = "ODIN-ChpSy2:Chop-FOC-401:"
# chic_root = "TBL-ChpSy1:Chop-CHIC-001:"
vacuum_pv_root = "ODIN-VacBnkr:Vac-VGP-"


devices = dict(
    bpc2_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{bpc2_pv_root}ChopState_R",
        visibility=(),
    ),
    bpc2_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",  # Should be EpicsAnalogMoveable later
        description="The current speed.",
        readpv=f"{bpc2_pv_root}Spd_R",
        writepv=f"{bpc2_pv_root}Spd_S",
        precision=0.1,
        mapping={"14 Hz": 14, "7 Hz": 7, "0 Hz": 0},
    ),
    bpc2_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{bpc2_pv_root}ChopDly-S",
        writepv=f"{bpc2_pv_root}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    bpc2_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="bpc2_chopper_delay",
        mapped_speed_dev="bpc2_chopper_speed",
        offset=0.0,
        unit="degrees",
    ),
    bpc2_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{bpc2_pv_root}DiffTSSamples",
        unit="ns",
        visibility=(
            "metadata",
            "namespace",
        ),
    ),
    bpc2_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{bpc2_pv_root}InPhs_R",
    ),
    bpc2_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{bpc2_pv_root}Pos_R",
        writepv=f"{bpc2_pv_root}ParkAngle_S",
    ),
    bpc2_chopper=device(
        "nicos_ess.devices.epics.chopper.OdinChopperController",
        description="The chopper controller",
        pv_root=bpc2_pv_root,
        monitor=True,
        slit_edges=[[0.0, 67.49]],
        mapping={
            "Start": "start",
            "AStart": "a_start",
            "Stop": "stop",
            "Park": "park",
        },
        speed="bpc2_chopper_speed",
        resolver_offset=108.05,
        tdc_offset=108.05,
        spin_direction="CW",
    ),
    bpc2_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv=f"{vacuum_pv_root}103:PrsR",
        fmtstr="%.2e",
    ),
    foc2_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{foc2_pv_root}ChopState_R",
        visibility=(),
    ),
    foc2_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{foc2_pv_root}Spd_R",
        writepv=f"{foc2_pv_root}Spd_S",
        precision=0.1,
        mapping={"14 Hz": 14, "7 Hz": 7, "0 Hz": 0, "21 Hz": 21, "42 Hz": 42},
    ),
    foc2_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{foc2_pv_root}ChopDly-S",
        writepv=f"{foc2_pv_root}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    foc2_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc2_chopper_delay",
        mapped_speed_dev="foc2_chopper_speed",
        offset=0.0,
        unit="degrees",
    ),
    foc2_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{foc2_pv_root}DiffTSSamples",
        unit="ns",
        visibility=("metadata", "namespace"),
    ),
    foc2_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{foc2_pv_root}InPhs_R",
    ),
    foc2_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{foc2_pv_root}Pos_R",
        writepv=f"{foc2_pv_root}ParkAngle_S",
    ),
    foc2_chopper=device(
        "nicos_ess.devices.epics.chopper.OdinChopperController",
        description="The chopper controller",
        pv_root=foc2_pv_root,
        monitor=True,
        slit_edges=[
            [0.0, 34.31],
            [60.625, 93.525],
            [128.155, 161.695],
            [191.47, 225.62],
            [250.85, 285.22],
            [306.54, 341.43],
        ],
        mapping={"Start": "start", "AStart": "a_start", "Stop": "stop", "Park": "park"},
        speed="foc2_chopper_speed",
        resolver_offset=49.995,
        tdc_offset=49.995,
        spin_direction="CCW",
    ),
    foc2_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv=f"{vacuum_pv_root}103:PrsR",
        fmtstr="%.2e",
    ),
    foc3_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{foc3_pv_root}ChopState_R",
        visibility=(),
    ),
    foc3_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{foc3_pv_root}Spd_R",
        writepv=f"{foc3_pv_root}Spd_S",
        precision=0.1,
        mapping={"14 Hz": 14, "7 Hz": 7, "0 Hz": 0, "28 Hz": 28},
    ),
    foc3_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{foc3_pv_root}ChopDly-S",
        writepv=f"{foc3_pv_root}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    foc3_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc3_chopper_delay",
        mapped_speed_dev="foc3_chopper_speed",
        offset=0.0,
        unit="degrees",
    ),
    foc3_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{foc3_pv_root}DiffTSSamples",
        unit="ns",
        visibility=("metadata", "namespace"),
    ),
    foc3_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{foc3_pv_root}InPhs_R",
    ),
    foc3_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{foc3_pv_root}Pos_R",
        writepv=f"{foc3_pv_root}ParkAngle_S",
    ),
    foc3_chopper=device(
        "nicos_ess.devices.epics.chopper.OdinChopperController",
        description="The chopper controller",
        pv_root=foc3_pv_root,
        monitor=True,
        slit_edges=[
            [0.0, 36.06],
            [78.95, 119.27],
            [142.355, 181.965],
            [201.82, 240.76],
            [257.575, 295.885],
            [309.86, 347.58],
        ],
        mapping={"Start": "start", "AStart": "a_start", "Stop": "stop", "Park": "park"},
        speed="foc3_chopper_speed",
        resolver_offset=35.89,
        tdc_offset=35.89,
        spin_direction="CW",
    ),
    foc3_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv=f"{vacuum_pv_root}105:PrsR",
        fmtstr="%.2e",
    ),
    foc4_chopper_status=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper status.",
        readpv=f"{foc4_pv_root}ChopState_R",
        visibility=(),
    ),
    foc4_chopper_speed=device(
        "nicos_ess.devices.epics.pva.EpicsManualMappedAnalogMoveable",
        description="The current speed.",
        readpv=f"{foc4_pv_root}Spd_R",
        writepv=f"{foc4_pv_root}Spd_S",
        precision=0.1,
        mapping={"14 Hz": 14, "7 Hz": 7, "0 Hz": 0},
    ),
    foc4_chopper_delay=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The current delay.",
        readpv=f"{foc4_pv_root}ChopDly-S",
        writepv=f"{foc4_pv_root}ChopDly-S",
        abslimits=(0.0, 0.0),
    ),
    foc4_chopper_phase=device(
        "nicos_ess.devices.transformer_devices.ChopperPhase",
        description="The phase of the chopper.",
        phase_ns_dev="foc4_chopper_delay",
        mapped_speed_dev="foc4_chopper_speed",
        offset=0.0,
        unit="degrees",
    ),
    foc4_chopper_delay_errors=device(
        "nicos_ess.devices.epics.chopper_delay_error.ChopperDelayError",
        description="The current delay.",
        readpv=f"{foc4_pv_root}DiffTSSamples",
        unit="ns",
        visibility=("metadata", "namespace"),
    ),
    foc4_chopper_phased=device(
        "nicos_ess.devices.epics.pva.EpicsMappedReadable",
        description="The chopper is in phase.",
        readpv=f"{foc4_pv_root}InPhs_R",
    ),
    foc4_chopper_park_angle=device(
        "nicos_ess.devices.epics.pva.EpicsAnalogMoveable",
        description="The chopper's park angle.",
        readpv=f"{foc4_pv_root}Pos_R",
        writepv=f"{foc4_pv_root}ParkAngle_S",
    ),
    foc4_chopper=device(
        "nicos_ess.devices.epics.chopper.OdinChopperController",
        description="The chopper controller",
        pv_root=foc4_pv_root,
        monitor=True,
        slit_edges=[
            [0.0, 32.98],
            [44.52, 76.34],
            [86.27, 117.01],
            [125.645, 154.915],
            [162.125, 190.895],
            [197.66, 224.42],
        ],
        mapping={"Start": "start", "AStart": "a_start", "Stop": "stop", "Park": "park"},
        speed="foc4_chopper_speed",
        resolver_offset=112.98,
        tdc_offset=112.98,
        spin_direction="CW",
    ),
    foc4_vacuum=device(
        "nicos_ess.devices.epics.pva.EpicsReadable",
        description="The vacuum pressure",
        readpv=f"{vacuum_pv_root}107:PrsR",  # same as foc
        fmtstr="%.2e",
    ),
)
