description = "The just-bin-it histogrammer."

excludes = ["livedata"]

devices = dict(
    jbi_detector=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItDetector",
        description="The just-bin-it histogrammer",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="",
        event_schema="ev44",
        hist_schema="hs01",
        liveinterval=1,
        command_topic="odin_jbi_commands",
        response_topic="odin_jbi_responses",
        statustopic=["odin_jbi_heartbeat"],
        images=["monitor_1", "monitor_2", "monitor_3"],
        timers=["timer"],
    ),
    timer=device(
        "nicos_ess.devices.timer.TimerChannel",
        description="Timer",
        fmtstr="%.2f",
        unit="s",
    ),
    monitor_1=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="Beam monitor 1 just-bin-it channel",
        hist_topic="odin_visualisation",
        data_topic="odin_beam_monitor",
        source="cbm1",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="ADC counts",
        hist_type="1-D TOF",
        det_width=1,
        det_height=1,
        det_range=(0, 100),
        tof_range=(0, 71428571),
        num_bins=714,
        input_schema="da00",
    ),
    monitor_2=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="Beam monitor 2 just-bin-it channel",
        hist_topic="odin_visualisation",
        data_topic="odin_beam_monitor",
        source="cbm2",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="ADC counts",
        hist_type="1-D TOF",
        det_width=1,
        det_height=1,
        det_range=(0, 100),
        tof_range=(0, 71428571),
        num_bins=714,
        input_schema="da00",
    ),
    monitor_3=device(
        "nicos_ess.devices.datasources.just_bin_it.JustBinItImage",
        description="Beam monitor 3 just-bin-it channel",
        hist_topic="odin_visualisation",
        data_topic="odin_beam_monitor",
        source="cbm3",
        brokers=configdata("config.KAFKA_BROKERS"),
        unit="ADC counts",
        hist_type="1-D TOF",
        det_width=1,
        det_height=1,
        det_range=(0, 100),
        tof_range=(0, 71428571),
        num_bins=714,
        input_schema="da00",
    ),
)
