description = "Julabo F25HL"

pv_root = "E04:JULABOF25HL-003:"

devices = dict(
    T_julabo_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The temperature",
        readpv=f"{pv_root}TEMP",
        writepv=f"{pv_root}TEMP:SP1",
        targetpv=f"{pv_root}TEMP:SP1:RBV",
        abslimits=(-1e308, 1e308),
    ),
    julabo_mode_003=device(
        "nicos.devices.epics.pva.EpicsMappedMoveable",
        description="The status",
        readpv=f"{pv_root}MODE",
        writepv=f"{pv_root}MODE:SP",
    ),
    T_julabo_external_003=device(
        "nicos.devices.epics.pva.EpicsReadable",
        description="The external sensor temperature",
        readpv=f"{pv_root}EXTT",
    ),
    julabo_external_enabled_003=device(
        "nicos.devices.epics.pva.EpicsMappedMoveable",
        description="Use external or internal sensor",
        readpv=f"{pv_root}EXTSENS",
        writepv=f"{pv_root}EXTSENS:SP",
    ),
    julabo_internal_P_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The internal P value",
        readpv=f"{pv_root}INTP",
        writepv=f"{pv_root}INTP:SP",
        visibility=(),
        abslimits=(-1e308, 1e308),
    ),
    julabo_internal_I_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The internal I value",
        readpv=f"{pv_root}INTI",
        writepv=f"{pv_root}INTI:SP",
        visibility=(),
        abslimits=(-1e308, 1e308),
    ),
    julabo_internal_D_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The internal D value",
        readpv=f"{pv_root}INTD",
        writepv=f"{pv_root}INTD:SP",
        visibility=(),
        abslimits=(-1e308, 1e308),
    ),
    julabo_safety_003=device(
        "nicos.devices.epics.pva.EpicsReadable",
        description="The safety sensor temperature",
        readpv=f"{pv_root}TSAFE",
        visibility=(),
    ),
    julabo_max_cooling_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The maximum cooling power %",
        readpv=f"{pv_root}MAX:COOL:RBV",
        writepv=f"{pv_root}MAX:COOL",
        visibility=(),
        abslimits=(-1e308, 1e308),
    ),
    julabo_max_heating_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The maximum heating power %",
        readpv=f"{pv_root}MAX:HEAT:RBV",
        writepv=f"{pv_root}MAX:HEAT",
        visibility=(),
        abslimits=(-1e308, 1e308),
    ),
    julabo_heating_power_003=device(
        "nicos.devices.epics.pva.EpicsReadable",
        description="The heating power being used %",
        readpv=f"{pv_root}POWER",
        visibility=(),
    ),
    julabo_internal_slope_003=device(
        "nicos.devices.epics.pva.EpicsReadable",
        description="The internal slope",
        readpv=f"{pv_root}SI:SLOPE:RBV",
        visibility=(),
    ),
    julabo_external_P_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The internal P value",
        readpv=f"{pv_root}EXTP",
        writepv=f"{pv_root}EXTP:SP",
        visibility=(),
        abslimits=(-1e308, 1e308),
    ),
    julabo_external_I_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The internal I value",
        readpv=f"{pv_root}EXTI",
        writepv=f"{pv_root}EXTI:SP",
        visibility=(),
        abslimits=(-1e308, 1e308),
    ),
    julabo_external_D_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The internal D value",
        readpv=f"{pv_root}EXTD",
        writepv=f"{pv_root}EXTD:SP",
        visibility=(),
        abslimits=(-1e308, 1e308),
    ),
    julabo_high_limit_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The high temp warning limit",
        readpv=f"{pv_root}HILIMIT",
        writepv=f"{pv_root}HILIMIT:SP",
        visibility=(),
        abslimits=(-1e308, 1e308),
    ),
    julabo_low_limit_003=device(
        "nicos.devices.epics.pva.EpicsAnalogMoveable",
        description="The low temp warning limit",
        readpv=f"{pv_root}LOWLIMIT",
        writepv=f"{pv_root}LOWLIMIT:SP",
        visibility=(),
        abslimits=(-1e308, 1e308),
    ),
    julabo_status_003=device(
        "nicos.devices.epics.pva.EpicsReadable",
        description="The status",
        readpv=f"{pv_root}STATUS",
        visibility=(),
    ),
    julabo_version_003=device(
        "nicos.devices.epics.pva.EpicsStringReadable",
        description="The software version",
        readpv=f"{pv_root}VERSION",
        visibility=(),
    ),
)
